language: node_js
node_js: stable
cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

script:
  - npm run build:travis

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master