{
"region": "chn-tianjin",
"zone": "ksywq",
"env":"online",
"job_name":"mione-yewujiankong-china-jvm",
"scrape_interval":"1m",
"scrape_timeout":"10s",
"metrics_path":"/jvm",
"honor_labels":false,
"honor_timestamps":false,
"scheme":"http",
"relabel_configs":[
{
"regex":"(.*)",
"target_label":"system",
"replacement":"mione",
"action":"replace",
"separator":";"
},
{
"source_labels":[
"__address__"
],
"regex":"(\\d+\\.\\d+\\.\\d+\\.\\d+).*",
"target_label":"ip",
"replacement":"$1",
"action":"replace"
}
],
"http_sd_configs":[
{
"url":"http://prometheus-agent:8080/prometheus/getips?type=2"
}
]
}