package run.mone.mcp.multimodal.test;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.io.TempDir;
import run.mone.mcp.multimodal.service.MultimodalService;

import java.io.File;
import java.nio.file.Path;

/**
 * 多模态界面操作服务测试类
 */
public class MultimodalServiceTest {

    private MultimodalService multimodalService;
    
    @BeforeEach
    public void setup() {
        multimodalService = new MultimodalService();
    }
    
    @Test
    @DisplayName("测试截取屏幕并保存为PNG - 自动生成文件名")
    public void testCaptureScreenToPngWithAutoGeneratedFilename() {
        // 使用默认文件路径（自动生成文件名）
        String result = multimodalService.captureMacScreenshot(null).blockFirst();

//        String result = multimodalService.captureEachScreenSeparately(null).blockFirst();

        // 验证结果中包含成功信息
        System.out.println("返回消息: " + result);
    }
    

}