apiVersion: apps/v1
kind: Deployment
metadata:
  name: hera-demo-client
  namespace: hera-namespace
  labels:
    app: hera-demo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hera-demo-client
  template:
    metadata:
      labels:
        app: hera-demo-client
    spec:
      containers:
      - name: hera-demo-client-container
        image: herahub/opensource-pub:hera-demo-client-v2
        env:
          - name: host.ip
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: node.ip
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: MIONE_PROJECT_ENV_NAME
            value: dev
          - name: PROMETHEUS_PORT
            value: '55423'
          - name: MIONE_PROJECT_ENV_ID
            value: '2'
          - name: APPLICATION
            value: 2_hera_demo_client
          - name: serverEnv
            value: dev
        volumeMounts:
          - name: log-path
            mountPath: /home/work/log
        resources:
          limits:
            cpu: '500m'
            memory: 2Gi

      - name: log-agent
        image: herahub/opensource-pub:log-agent-v3
        volumeMounts:
        - mountPath: "/home/work/log"
          name: log-path
        resources:
          limits:
            cpu: '300m'
            memory: 1Gi
      volumes:
      - name: log-path
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hera-demo-client
  namespace: hera-namespace
  labels:
    app: hera-demo-client
spec:
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
  selector:
    app: hera-demo-client
  clusterIP: None