apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-manager
  namespace: ozhera-namespace
  labels:
    app: log-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-manager
  template:
    metadata:
      labels:
        app: log-manager
    spec:
      containers:
      - name: log-manager-container
        image: herahub/opensource-pub:log-manager-v1-release
        resources:
          limits:
            cpu: '500m'
            memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: log-manager
  namespace: ozhera-namespace
  labels:
    app: log-manager
spec:
  ports:
    - port: 7788
      targetPort: 7788
      protocol: TCP
  selector:
    app: log-manager
  clusterIP: None
