// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sidecar.proto

package run.mone.mesh.bo;

public interface PushMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:run.mone.mesh.bo.PushMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>bytes data = 3;</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>int32 cmd = 4;</code>
   */
  int getCmd();

  /**
   * <code>string app = 5;</code>
   */
  java.lang.String getApp();
  /**
   * <code>string app = 5;</code>
   */
  com.google.protobuf.ByteString
      getAppBytes();
}
