// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sidecar.proto

package run.mone.mesh.bo;

/**
 * Protobuf type {@code run.mone.mesh.bo.SideCarRequest}
 */
public final class SideCarRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:run.mone.mesh.bo.SideCarRequest)
    SideCarRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SideCarRequest.newBuilder() to construct.
  private SideCarRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SideCarRequest() {
    serviceName_ = "";
    methodName_ = "";
    paramTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    group_ = "";
    version_ = "";
    id_ = "";
    app_ = "";
    cmd_ = "";
    data_ = com.google.protobuf.ByteString.EMPTY;
    type_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SideCarRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SideCarRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            serviceName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            methodName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              paramTypes_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            paramTypes_.add(s);
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              params_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            params_.add(s);
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            group_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          case 58: {
            run.mone.mesh.bo.SideCarAddress.Builder subBuilder = null;
            if (address_ != null) {
              subBuilder = address_.toBuilder();
            }
            address_ = input.readMessage(run.mone.mesh.bo.SideCarAddress.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(address_);
              address_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            app_ = s;
            break;
          }
          case 80: {

            timeout_ = input.readInt64();
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            cmd_ = s;
            break;
          }
          case 98: {

            data_ = input.readBytes();
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 112: {

            reqId_ = input.readInt32();
            break;
          }
          case 122: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              attachments_ = com.google.protobuf.MapField.newMapField(
                  AttachmentsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000004;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            attachments__ = input.readMessage(
                AttachmentsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            attachments_.getMutableMap().put(
                attachments__.getKey(), attachments__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        paramTypes_ = paramTypes_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        params_ = params_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return run.mone.mesh.bo.Sidecar.internal_static_run_mone_mesh_bo_SideCarRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 15:
        return internalGetAttachments();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return run.mone.mesh.bo.Sidecar.internal_static_run_mone_mesh_bo_SideCarRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            run.mone.mesh.bo.SideCarRequest.class, run.mone.mesh.bo.SideCarRequest.Builder.class);
  }

  public static final int SERVICENAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object serviceName_;
  /**
   * <code>string serviceName = 1;</code>
   * @return The serviceName.
   */
  @java.lang.Override
  public java.lang.String getServiceName() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceName_ = s;
      return s;
    }
  }
  /**
   * <code>string serviceName = 1;</code>
   * @return The bytes for serviceName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceNameBytes() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHODNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object methodName_;
  /**
   * <code>string methodName = 2;</code>
   * @return The methodName.
   */
  @java.lang.Override
  public java.lang.String getMethodName() {
    java.lang.Object ref = methodName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      methodName_ = s;
      return s;
    }
  }
  /**
   * <code>string methodName = 2;</code>
   * @return The bytes for methodName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMethodNameBytes() {
    java.lang.Object ref = methodName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      methodName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAMTYPES_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList paramTypes_;
  /**
   * <code>repeated string paramTypes = 3;</code>
   * @return A list containing the paramTypes.
   */
  public com.google.protobuf.ProtocolStringList
      getParamTypesList() {
    return paramTypes_;
  }
  /**
   * <code>repeated string paramTypes = 3;</code>
   * @return The count of paramTypes.
   */
  public int getParamTypesCount() {
    return paramTypes_.size();
  }
  /**
   * <code>repeated string paramTypes = 3;</code>
   * @param index The index of the element to return.
   * @return The paramTypes at the given index.
   */
  public java.lang.String getParamTypes(int index) {
    return paramTypes_.get(index);
  }
  /**
   * <code>repeated string paramTypes = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the paramTypes at the given index.
   */
  public com.google.protobuf.ByteString
      getParamTypesBytes(int index) {
    return paramTypes_.getByteString(index);
  }

  public static final int PARAMS_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList params_;
  /**
   * <code>repeated string params = 4;</code>
   * @return A list containing the params.
   */
  public com.google.protobuf.ProtocolStringList
      getParamsList() {
    return params_;
  }
  /**
   * <code>repeated string params = 4;</code>
   * @return The count of params.
   */
  public int getParamsCount() {
    return params_.size();
  }
  /**
   * <code>repeated string params = 4;</code>
   * @param index The index of the element to return.
   * @return The params at the given index.
   */
  public java.lang.String getParams(int index) {
    return params_.get(index);
  }
  /**
   * <code>repeated string params = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the params at the given index.
   */
  public com.google.protobuf.ByteString
      getParamsBytes(int index) {
    return params_.getByteString(index);
  }

  public static final int GROUP_FIELD_NUMBER = 5;
  private volatile java.lang.Object group_;
  /**
   * <code>string group = 5;</code>
   * @return The group.
   */
  @java.lang.Override
  public java.lang.String getGroup() {
    java.lang.Object ref = group_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      group_ = s;
      return s;
    }
  }
  /**
   * <code>string group = 5;</code>
   * @return The bytes for group.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupBytes() {
    java.lang.Object ref = group_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      group_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 6;
  private volatile java.lang.Object version_;
  /**
   * <code>string version = 6;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 6;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 7;
  private run.mone.mesh.bo.SideCarAddress address_;
  /**
   * <code>.run.mone.mesh.bo.SideCarAddress address = 7;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return address_ != null;
  }
  /**
   * <code>.run.mone.mesh.bo.SideCarAddress address = 7;</code>
   * @return The address.
   */
  @java.lang.Override
  public run.mone.mesh.bo.SideCarAddress getAddress() {
    return address_ == null ? run.mone.mesh.bo.SideCarAddress.getDefaultInstance() : address_;
  }
  /**
   * <code>.run.mone.mesh.bo.SideCarAddress address = 7;</code>
   */
  @java.lang.Override
  public run.mone.mesh.bo.SideCarAddressOrBuilder getAddressOrBuilder() {
    return getAddress();
  }

  public static final int ID_FIELD_NUMBER = 8;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 8;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 8;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APP_FIELD_NUMBER = 9;
  private volatile java.lang.Object app_;
  /**
   * <code>string app = 9;</code>
   * @return The app.
   */
  @java.lang.Override
  public java.lang.String getApp() {
    java.lang.Object ref = app_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      app_ = s;
      return s;
    }
  }
  /**
   * <code>string app = 9;</code>
   * @return The bytes for app.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppBytes() {
    java.lang.Object ref = app_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      app_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEOUT_FIELD_NUMBER = 10;
  private long timeout_;
  /**
   * <code>int64 timeout = 10;</code>
   * @return The timeout.
   */
  @java.lang.Override
  public long getTimeout() {
    return timeout_;
  }

  public static final int CMD_FIELD_NUMBER = 11;
  private volatile java.lang.Object cmd_;
  /**
   * <code>string cmd = 11;</code>
   * @return The cmd.
   */
  @java.lang.Override
  public java.lang.String getCmd() {
    java.lang.Object ref = cmd_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cmd_ = s;
      return s;
    }
  }
  /**
   * <code>string cmd = 11;</code>
   * @return The bytes for cmd.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCmdBytes() {
    java.lang.Object ref = cmd_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cmd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 12;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>bytes data = 12;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  public static final int TYPE_FIELD_NUMBER = 13;
  private volatile java.lang.Object type_;
  /**
   * <code>string type = 13;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 13;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQID_FIELD_NUMBER = 14;
  private int reqId_;
  /**
   * <code>int32 reqId = 14;</code>
   * @return The reqId.
   */
  @java.lang.Override
  public int getReqId() {
    return reqId_;
  }

  public static final int ATTACHMENTS_FIELD_NUMBER = 15;
  private static final class AttachmentsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                run.mone.mesh.bo.Sidecar.internal_static_run_mone_mesh_bo_SideCarRequest_AttachmentsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> attachments_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetAttachments() {
    if (attachments_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AttachmentsDefaultEntryHolder.defaultEntry);
    }
    return attachments_;
  }

  public int getAttachmentsCount() {
    return internalGetAttachments().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; attachments = 15;</code>
   */

  @java.lang.Override
  public boolean containsAttachments(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetAttachments().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAttachmentsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getAttachments() {
    return getAttachmentsMap();
  }
  /**
   * <code>map&lt;string, string&gt; attachments = 15;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getAttachmentsMap() {
    return internalGetAttachments().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; attachments = 15;</code>
   */
  @java.lang.Override

  public java.lang.String getAttachmentsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAttachments().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; attachments = 15;</code>
   */
  @java.lang.Override

  public java.lang.String getAttachmentsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAttachments().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getServiceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceName_);
    }
    if (!getMethodNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, methodName_);
    }
    for (int i = 0; i < paramTypes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, paramTypes_.getRaw(i));
    }
    for (int i = 0; i < params_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, params_.getRaw(i));
    }
    if (!getGroupBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, group_);
    }
    if (!getVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, version_);
    }
    if (address_ != null) {
      output.writeMessage(7, getAddress());
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, id_);
    }
    if (!getAppBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, app_);
    }
    if (timeout_ != 0L) {
      output.writeInt64(10, timeout_);
    }
    if (!getCmdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, cmd_);
    }
    if (!data_.isEmpty()) {
      output.writeBytes(12, data_);
    }
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, type_);
    }
    if (reqId_ != 0) {
      output.writeInt32(14, reqId_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetAttachments(),
        AttachmentsDefaultEntryHolder.defaultEntry,
        15);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getServiceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceName_);
    }
    if (!getMethodNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, methodName_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < paramTypes_.size(); i++) {
        dataSize += computeStringSizeNoTag(paramTypes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getParamTypesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < params_.size(); i++) {
        dataSize += computeStringSizeNoTag(params_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getParamsList().size();
    }
    if (!getGroupBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, group_);
    }
    if (!getVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, version_);
    }
    if (address_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getAddress());
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, id_);
    }
    if (!getAppBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, app_);
    }
    if (timeout_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, timeout_);
    }
    if (!getCmdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, cmd_);
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(12, data_);
    }
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, type_);
    }
    if (reqId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, reqId_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetAttachments().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      attachments__ = AttachmentsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, attachments__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof run.mone.mesh.bo.SideCarRequest)) {
      return super.equals(obj);
    }
    run.mone.mesh.bo.SideCarRequest other = (run.mone.mesh.bo.SideCarRequest) obj;

    if (!getServiceName()
        .equals(other.getServiceName())) return false;
    if (!getMethodName()
        .equals(other.getMethodName())) return false;
    if (!getParamTypesList()
        .equals(other.getParamTypesList())) return false;
    if (!getParamsList()
        .equals(other.getParamsList())) return false;
    if (!getGroup()
        .equals(other.getGroup())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (!getId()
        .equals(other.getId())) return false;
    if (!getApp()
        .equals(other.getApp())) return false;
    if (getTimeout()
        != other.getTimeout()) return false;
    if (!getCmd()
        .equals(other.getCmd())) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (getReqId()
        != other.getReqId()) return false;
    if (!internalGetAttachments().equals(
        other.internalGetAttachments())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVICENAME_FIELD_NUMBER;
    hash = (53 * hash) + getServiceName().hashCode();
    hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
    hash = (53 * hash) + getMethodName().hashCode();
    if (getParamTypesCount() > 0) {
      hash = (37 * hash) + PARAMTYPES_FIELD_NUMBER;
      hash = (53 * hash) + getParamTypesList().hashCode();
    }
    if (getParamsCount() > 0) {
      hash = (37 * hash) + PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getParamsList().hashCode();
    }
    hash = (37 * hash) + GROUP_FIELD_NUMBER;
    hash = (53 * hash) + getGroup().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + APP_FIELD_NUMBER;
    hash = (53 * hash) + getApp().hashCode();
    hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeout());
    hash = (37 * hash) + CMD_FIELD_NUMBER;
    hash = (53 * hash) + getCmd().hashCode();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + REQID_FIELD_NUMBER;
    hash = (53 * hash) + getReqId();
    if (!internalGetAttachments().getMap().isEmpty()) {
      hash = (37 * hash) + ATTACHMENTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAttachments().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static run.mone.mesh.bo.SideCarRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static run.mone.mesh.bo.SideCarRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static run.mone.mesh.bo.SideCarRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static run.mone.mesh.bo.SideCarRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static run.mone.mesh.bo.SideCarRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static run.mone.mesh.bo.SideCarRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static run.mone.mesh.bo.SideCarRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static run.mone.mesh.bo.SideCarRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static run.mone.mesh.bo.SideCarRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static run.mone.mesh.bo.SideCarRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static run.mone.mesh.bo.SideCarRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static run.mone.mesh.bo.SideCarRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(run.mone.mesh.bo.SideCarRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code run.mone.mesh.bo.SideCarRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:run.mone.mesh.bo.SideCarRequest)
      run.mone.mesh.bo.SideCarRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return run.mone.mesh.bo.Sidecar.internal_static_run_mone_mesh_bo_SideCarRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 15:
          return internalGetAttachments();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 15:
          return internalGetMutableAttachments();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return run.mone.mesh.bo.Sidecar.internal_static_run_mone_mesh_bo_SideCarRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              run.mone.mesh.bo.SideCarRequest.class, run.mone.mesh.bo.SideCarRequest.Builder.class);
    }

    // Construct using run.mone.mesh.bo.SideCarRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      serviceName_ = "";

      methodName_ = "";

      paramTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      group_ = "";

      version_ = "";

      if (addressBuilder_ == null) {
        address_ = null;
      } else {
        address_ = null;
        addressBuilder_ = null;
      }
      id_ = "";

      app_ = "";

      timeout_ = 0L;

      cmd_ = "";

      data_ = com.google.protobuf.ByteString.EMPTY;

      type_ = "";

      reqId_ = 0;

      internalGetMutableAttachments().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return run.mone.mesh.bo.Sidecar.internal_static_run_mone_mesh_bo_SideCarRequest_descriptor;
    }

    @java.lang.Override
    public run.mone.mesh.bo.SideCarRequest getDefaultInstanceForType() {
      return run.mone.mesh.bo.SideCarRequest.getDefaultInstance();
    }

    @java.lang.Override
    public run.mone.mesh.bo.SideCarRequest build() {
      run.mone.mesh.bo.SideCarRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public run.mone.mesh.bo.SideCarRequest buildPartial() {
      run.mone.mesh.bo.SideCarRequest result = new run.mone.mesh.bo.SideCarRequest(this);
      int from_bitField0_ = bitField0_;
      result.serviceName_ = serviceName_;
      result.methodName_ = methodName_;
      if (((bitField0_ & 0x00000001) != 0)) {
        paramTypes_ = paramTypes_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.paramTypes_ = paramTypes_;
      if (((bitField0_ & 0x00000002) != 0)) {
        params_ = params_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.params_ = params_;
      result.group_ = group_;
      result.version_ = version_;
      if (addressBuilder_ == null) {
        result.address_ = address_;
      } else {
        result.address_ = addressBuilder_.build();
      }
      result.id_ = id_;
      result.app_ = app_;
      result.timeout_ = timeout_;
      result.cmd_ = cmd_;
      result.data_ = data_;
      result.type_ = type_;
      result.reqId_ = reqId_;
      result.attachments_ = internalGetAttachments();
      result.attachments_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof run.mone.mesh.bo.SideCarRequest) {
        return mergeFrom((run.mone.mesh.bo.SideCarRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(run.mone.mesh.bo.SideCarRequest other) {
      if (other == run.mone.mesh.bo.SideCarRequest.getDefaultInstance()) return this;
      if (!other.getServiceName().isEmpty()) {
        serviceName_ = other.serviceName_;
        onChanged();
      }
      if (!other.getMethodName().isEmpty()) {
        methodName_ = other.methodName_;
        onChanged();
      }
      if (!other.paramTypes_.isEmpty()) {
        if (paramTypes_.isEmpty()) {
          paramTypes_ = other.paramTypes_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureParamTypesIsMutable();
          paramTypes_.addAll(other.paramTypes_);
        }
        onChanged();
      }
      if (!other.params_.isEmpty()) {
        if (params_.isEmpty()) {
          params_ = other.params_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureParamsIsMutable();
          params_.addAll(other.params_);
        }
        onChanged();
      }
      if (!other.getGroup().isEmpty()) {
        group_ = other.group_;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getApp().isEmpty()) {
        app_ = other.app_;
        onChanged();
      }
      if (other.getTimeout() != 0L) {
        setTimeout(other.getTimeout());
      }
      if (!other.getCmd().isEmpty()) {
        cmd_ = other.cmd_;
        onChanged();
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (other.getReqId() != 0) {
        setReqId(other.getReqId());
      }
      internalGetMutableAttachments().mergeFrom(
          other.internalGetAttachments());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      run.mone.mesh.bo.SideCarRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (run.mone.mesh.bo.SideCarRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object serviceName_ = "";
    /**
     * <code>string serviceName = 1;</code>
     * @return The serviceName.
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string serviceName = 1;</code>
     * @return The bytes for serviceName.
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string serviceName = 1;</code>
     * @param value The serviceName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string serviceName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceName() {
      
      serviceName_ = getDefaultInstance().getServiceName();
      onChanged();
      return this;
    }
    /**
     * <code>string serviceName = 1;</code>
     * @param value The bytes for serviceName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object methodName_ = "";
    /**
     * <code>string methodName = 2;</code>
     * @return The methodName.
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string methodName = 2;</code>
     * @return The bytes for methodName.
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string methodName = 2;</code>
     * @param value The methodName to set.
     * @return This builder for chaining.
     */
    public Builder setMethodName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      methodName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string methodName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMethodName() {
      
      methodName_ = getDefaultInstance().getMethodName();
      onChanged();
      return this;
    }
    /**
     * <code>string methodName = 2;</code>
     * @param value The bytes for methodName to set.
     * @return This builder for chaining.
     */
    public Builder setMethodNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      methodName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList paramTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureParamTypesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        paramTypes_ = new com.google.protobuf.LazyStringArrayList(paramTypes_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string paramTypes = 3;</code>
     * @return A list containing the paramTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getParamTypesList() {
      return paramTypes_.getUnmodifiableView();
    }
    /**
     * <code>repeated string paramTypes = 3;</code>
     * @return The count of paramTypes.
     */
    public int getParamTypesCount() {
      return paramTypes_.size();
    }
    /**
     * <code>repeated string paramTypes = 3;</code>
     * @param index The index of the element to return.
     * @return The paramTypes at the given index.
     */
    public java.lang.String getParamTypes(int index) {
      return paramTypes_.get(index);
    }
    /**
     * <code>repeated string paramTypes = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paramTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getParamTypesBytes(int index) {
      return paramTypes_.getByteString(index);
    }
    /**
     * <code>repeated string paramTypes = 3;</code>
     * @param index The index to set the value at.
     * @param value The paramTypes to set.
     * @return This builder for chaining.
     */
    public Builder setParamTypes(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureParamTypesIsMutable();
      paramTypes_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string paramTypes = 3;</code>
     * @param value The paramTypes to add.
     * @return This builder for chaining.
     */
    public Builder addParamTypes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureParamTypesIsMutable();
      paramTypes_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string paramTypes = 3;</code>
     * @param values The paramTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllParamTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureParamTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, paramTypes_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string paramTypes = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearParamTypes() {
      paramTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string paramTypes = 3;</code>
     * @param value The bytes of the paramTypes to add.
     * @return This builder for chaining.
     */
    public Builder addParamTypesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureParamTypesIsMutable();
      paramTypes_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureParamsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        params_ = new com.google.protobuf.LazyStringArrayList(params_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string params = 4;</code>
     * @return A list containing the params.
     */
    public com.google.protobuf.ProtocolStringList
        getParamsList() {
      return params_.getUnmodifiableView();
    }
    /**
     * <code>repeated string params = 4;</code>
     * @return The count of params.
     */
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <code>repeated string params = 4;</code>
     * @param index The index of the element to return.
     * @return The params at the given index.
     */
    public java.lang.String getParams(int index) {
      return params_.get(index);
    }
    /**
     * <code>repeated string params = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the params at the given index.
     */
    public com.google.protobuf.ByteString
        getParamsBytes(int index) {
      return params_.getByteString(index);
    }
    /**
     * <code>repeated string params = 4;</code>
     * @param index The index to set the value at.
     * @param value The params to set.
     * @return This builder for chaining.
     */
    public Builder setParams(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
      params_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string params = 4;</code>
     * @param value The params to add.
     * @return This builder for chaining.
     */
    public Builder addParams(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
      params_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string params = 4;</code>
     * @param values The params to add.
     * @return This builder for chaining.
     */
    public Builder addAllParams(
        java.lang.Iterable<java.lang.String> values) {
      ensureParamsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, params_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string params = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearParams() {
      params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string params = 4;</code>
     * @param value The bytes of the params to add.
     * @return This builder for chaining.
     */
    public Builder addParamsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureParamsIsMutable();
      params_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object group_ = "";
    /**
     * <code>string group = 5;</code>
     * @return The group.
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string group = 5;</code>
     * @return The bytes for group.
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string group = 5;</code>
     * @param value The group to set.
     * @return This builder for chaining.
     */
    public Builder setGroup(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      group_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string group = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroup() {
      
      group_ = getDefaultInstance().getGroup();
      onChanged();
      return this;
    }
    /**
     * <code>string group = 5;</code>
     * @param value The bytes for group to set.
     * @return This builder for chaining.
     */
    public Builder setGroupBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      group_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 6;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 6;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 6;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string version = 6;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private run.mone.mesh.bo.SideCarAddress address_;
    private com.google.protobuf.SingleFieldBuilderV3<
        run.mone.mesh.bo.SideCarAddress, run.mone.mesh.bo.SideCarAddress.Builder, run.mone.mesh.bo.SideCarAddressOrBuilder> addressBuilder_;
    /**
     * <code>.run.mone.mesh.bo.SideCarAddress address = 7;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return addressBuilder_ != null || address_ != null;
    }
    /**
     * <code>.run.mone.mesh.bo.SideCarAddress address = 7;</code>
     * @return The address.
     */
    public run.mone.mesh.bo.SideCarAddress getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? run.mone.mesh.bo.SideCarAddress.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <code>.run.mone.mesh.bo.SideCarAddress address = 7;</code>
     */
    public Builder setAddress(run.mone.mesh.bo.SideCarAddress value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
        onChanged();
      } else {
        addressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.run.mone.mesh.bo.SideCarAddress address = 7;</code>
     */
    public Builder setAddress(
        run.mone.mesh.bo.SideCarAddress.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
        onChanged();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.run.mone.mesh.bo.SideCarAddress address = 7;</code>
     */
    public Builder mergeAddress(run.mone.mesh.bo.SideCarAddress value) {
      if (addressBuilder_ == null) {
        if (address_ != null) {
          address_ =
            run.mone.mesh.bo.SideCarAddress.newBuilder(address_).mergeFrom(value).buildPartial();
        } else {
          address_ = value;
        }
        onChanged();
      } else {
        addressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.run.mone.mesh.bo.SideCarAddress address = 7;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = null;
        onChanged();
      } else {
        address_ = null;
        addressBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.run.mone.mesh.bo.SideCarAddress address = 7;</code>
     */
    public run.mone.mesh.bo.SideCarAddress.Builder getAddressBuilder() {
      
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.run.mone.mesh.bo.SideCarAddress address = 7;</code>
     */
    public run.mone.mesh.bo.SideCarAddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            run.mone.mesh.bo.SideCarAddress.getDefaultInstance() : address_;
      }
    }
    /**
     * <code>.run.mone.mesh.bo.SideCarAddress address = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        run.mone.mesh.bo.SideCarAddress, run.mone.mesh.bo.SideCarAddress.Builder, run.mone.mesh.bo.SideCarAddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            run.mone.mesh.bo.SideCarAddress, run.mone.mesh.bo.SideCarAddress.Builder, run.mone.mesh.bo.SideCarAddressOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 8;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 8;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 8;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 8;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object app_ = "";
    /**
     * <code>string app = 9;</code>
     * @return The app.
     */
    public java.lang.String getApp() {
      java.lang.Object ref = app_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        app_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string app = 9;</code>
     * @return The bytes for app.
     */
    public com.google.protobuf.ByteString
        getAppBytes() {
      java.lang.Object ref = app_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        app_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string app = 9;</code>
     * @param value The app to set.
     * @return This builder for chaining.
     */
    public Builder setApp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      app_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string app = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearApp() {
      
      app_ = getDefaultInstance().getApp();
      onChanged();
      return this;
    }
    /**
     * <code>string app = 9;</code>
     * @param value The bytes for app to set.
     * @return This builder for chaining.
     */
    public Builder setAppBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      app_ = value;
      onChanged();
      return this;
    }

    private long timeout_ ;
    /**
     * <code>int64 timeout = 10;</code>
     * @return The timeout.
     */
    @java.lang.Override
    public long getTimeout() {
      return timeout_;
    }
    /**
     * <code>int64 timeout = 10;</code>
     * @param value The timeout to set.
     * @return This builder for chaining.
     */
    public Builder setTimeout(long value) {
      
      timeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timeout = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeout() {
      
      timeout_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object cmd_ = "";
    /**
     * <code>string cmd = 11;</code>
     * @return The cmd.
     */
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cmd = 11;</code>
     * @return The bytes for cmd.
     */
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cmd = 11;</code>
     * @param value The cmd to set.
     * @return This builder for chaining.
     */
    public Builder setCmd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cmd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cmd = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearCmd() {
      
      cmd_ = getDefaultInstance().getCmd();
      onChanged();
      return this;
    }
    /**
     * <code>string cmd = 11;</code>
     * @param value The bytes for cmd to set.
     * @return This builder for chaining.
     */
    public Builder setCmdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cmd_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 12;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 12;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes data = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 13;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 13;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 13;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string type = 13;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private int reqId_ ;
    /**
     * <code>int32 reqId = 14;</code>
     * @return The reqId.
     */
    @java.lang.Override
    public int getReqId() {
      return reqId_;
    }
    /**
     * <code>int32 reqId = 14;</code>
     * @param value The reqId to set.
     * @return This builder for chaining.
     */
    public Builder setReqId(int value) {
      
      reqId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 reqId = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearReqId() {
      
      reqId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> attachments_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAttachments() {
      if (attachments_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttachmentsDefaultEntryHolder.defaultEntry);
      }
      return attachments_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableAttachments() {
      onChanged();;
      if (attachments_ == null) {
        attachments_ = com.google.protobuf.MapField.newMapField(
            AttachmentsDefaultEntryHolder.defaultEntry);
      }
      if (!attachments_.isMutable()) {
        attachments_ = attachments_.copy();
      }
      return attachments_;
    }

    public int getAttachmentsCount() {
      return internalGetAttachments().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; attachments = 15;</code>
     */

    @java.lang.Override
    public boolean containsAttachments(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAttachments().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttachmentsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAttachments() {
      return getAttachmentsMap();
    }
    /**
     * <code>map&lt;string, string&gt; attachments = 15;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getAttachmentsMap() {
      return internalGetAttachments().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; attachments = 15;</code>
     */
    @java.lang.Override

    public java.lang.String getAttachmentsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttachments().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; attachments = 15;</code>
     */
    @java.lang.Override

    public java.lang.String getAttachmentsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttachments().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearAttachments() {
      internalGetMutableAttachments().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; attachments = 15;</code>
     */

    public Builder removeAttachments(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAttachments().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableAttachments() {
      return internalGetMutableAttachments().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; attachments = 15;</code>
     */
    public Builder putAttachments(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAttachments().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; attachments = 15;</code>
     */

    public Builder putAllAttachments(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableAttachments().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:run.mone.mesh.bo.SideCarRequest)
  }

  // @@protoc_insertion_point(class_scope:run.mone.mesh.bo.SideCarRequest)
  private static final run.mone.mesh.bo.SideCarRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new run.mone.mesh.bo.SideCarRequest();
  }

  public static run.mone.mesh.bo.SideCarRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SideCarRequest>
      PARSER = new com.google.protobuf.AbstractParser<SideCarRequest>() {
    @java.lang.Override
    public SideCarRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SideCarRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SideCarRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SideCarRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public run.mone.mesh.bo.SideCarRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

