// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sidecar.proto

package run.mone.mesh.bo;

public final class Sidecar {
  private Sidecar() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_run_mone_mesh_bo_SideCarAddress_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_run_mone_mesh_bo_SideCarAddress_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_run_mone_mesh_bo_SideCarRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_run_mone_mesh_bo_SideCarRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_run_mone_mesh_bo_SideCarRequest_AttachmentsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_run_mone_mesh_bo_SideCarRequest_AttachmentsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_run_mone_mesh_bo_SideCarResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_run_mone_mesh_bo_SideCarResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_run_mone_mesh_bo_SideCarResponse_AttachmentsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_run_mone_mesh_bo_SideCarResponse_AttachmentsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_run_mone_mesh_bo_SideCarPushMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_run_mone_mesh_bo_SideCarPushMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_run_mone_mesh_bo_SideCarPushMsg_AttachmentsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_run_mone_mesh_bo_SideCarPushMsg_AttachmentsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsidecar.proto\022\020run.mone.mesh.bo\"7\n\016Sid" +
      "eCarAddress\022\n\n\002ip\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\022\013\n" +
      "\003app\030\003 \001(\t\"\216\003\n\016SideCarRequest\022\023\n\013service" +
      "Name\030\001 \001(\t\022\022\n\nmethodName\030\002 \001(\t\022\022\n\nparamT" +
      "ypes\030\003 \003(\t\022\016\n\006params\030\004 \003(\t\022\r\n\005group\030\005 \001(" +
      "\t\022\017\n\007version\030\006 \001(\t\0221\n\007address\030\007 \001(\0132 .ru" +
      "n.mone.mesh.bo.SideCarAddress\022\n\n\002id\030\010 \001(" +
      "\t\022\013\n\003app\030\t \001(\t\022\017\n\007timeout\030\n \001(\003\022\013\n\003cmd\030\013" +
      " \001(\t\022\014\n\004data\030\014 \001(\014\022\014\n\004type\030\r \001(\t\022\r\n\005reqI" +
      "d\030\016 \001(\005\022F\n\013attachments\030\017 \003(\01321.run.mone." +
      "mesh.bo.SideCarRequest.AttachmentsEntry\032" +
      "2\n\020AttachmentsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\t:\0028\001\"\273\001\n\017SideCarResponse\022\014\n\004code\030" +
      "\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\014\n\004data\030\003 \001(\014\022G\n\013" +
      "attachments\030\004 \003(\01322.run.mone.mesh.bo.Sid" +
      "eCarResponse.AttachmentsEntry\0322\n\020Attachm" +
      "entsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028" +
      "\001\"\360\001\n\016SideCarPushMsg\022\014\n\004code\030\001 \001(\005\022\017\n\007me" +
      "ssage\030\002 \001(\t\022\014\n\004data\030\003 \001(\014\022\013\n\003cmd\030\004 \001(\t\022\013" +
      "\n\003app\030\005 \001(\t\022\014\n\004type\030\006 \001(\t\022\r\n\005reqId\030\007 \001(\005" +
      "\022F\n\013attachments\030\010 \003(\01321.run.mone.mesh.bo" +
      ".SideCarPushMsg.AttachmentsEntry\0322\n\020Atta" +
      "chmentsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\0012\257\001\n\016SideCarService\022K\n\004call\022 .run.mo" +
      "ne.mesh.bo.SideCarRequest\032!.run.mone.mes" +
      "h.bo.SideCarResponse\022P\n\006listen\022 .run.mon" +
      "e.mesh.bo.SideCarRequest\032 .run.mone.mesh" +
      ".bo.SideCarPushMsg(\0010\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_run_mone_mesh_bo_SideCarAddress_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_run_mone_mesh_bo_SideCarAddress_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_run_mone_mesh_bo_SideCarAddress_descriptor,
        new java.lang.String[] { "Ip", "Port", "App", });
    internal_static_run_mone_mesh_bo_SideCarRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_run_mone_mesh_bo_SideCarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_run_mone_mesh_bo_SideCarRequest_descriptor,
        new java.lang.String[] { "ServiceName", "MethodName", "ParamTypes", "Params", "Group", "Version", "Address", "Id", "App", "Timeout", "Cmd", "Data", "Type", "ReqId", "Attachments", });
    internal_static_run_mone_mesh_bo_SideCarRequest_AttachmentsEntry_descriptor =
      internal_static_run_mone_mesh_bo_SideCarRequest_descriptor.getNestedTypes().get(0);
    internal_static_run_mone_mesh_bo_SideCarRequest_AttachmentsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_run_mone_mesh_bo_SideCarRequest_AttachmentsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_run_mone_mesh_bo_SideCarResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_run_mone_mesh_bo_SideCarResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_run_mone_mesh_bo_SideCarResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "Data", "Attachments", });
    internal_static_run_mone_mesh_bo_SideCarResponse_AttachmentsEntry_descriptor =
      internal_static_run_mone_mesh_bo_SideCarResponse_descriptor.getNestedTypes().get(0);
    internal_static_run_mone_mesh_bo_SideCarResponse_AttachmentsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_run_mone_mesh_bo_SideCarResponse_AttachmentsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_run_mone_mesh_bo_SideCarPushMsg_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_run_mone_mesh_bo_SideCarPushMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_run_mone_mesh_bo_SideCarPushMsg_descriptor,
        new java.lang.String[] { "Code", "Message", "Data", "Cmd", "App", "Type", "ReqId", "Attachments", });
    internal_static_run_mone_mesh_bo_SideCarPushMsg_AttachmentsEntry_descriptor =
      internal_static_run_mone_mesh_bo_SideCarPushMsg_descriptor.getNestedTypes().get(0);
    internal_static_run_mone_mesh_bo_SideCarPushMsg_AttachmentsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_run_mone_mesh_bo_SideCarPushMsg_AttachmentsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
