// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sidecar.proto

package run.mone.mesh.bo;

public interface SideCarRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:run.mone.mesh.bo.SideCarRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serviceName = 1;</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 1;</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string methodName = 2;</code>
   * @return The methodName.
   */
  java.lang.String getMethodName();
  /**
   * <code>string methodName = 2;</code>
   * @return The bytes for methodName.
   */
  com.google.protobuf.ByteString
      getMethodNameBytes();

  /**
   * <code>repeated string paramTypes = 3;</code>
   * @return A list containing the paramTypes.
   */
  java.util.List<java.lang.String>
      getParamTypesList();
  /**
   * <code>repeated string paramTypes = 3;</code>
   * @return The count of paramTypes.
   */
  int getParamTypesCount();
  /**
   * <code>repeated string paramTypes = 3;</code>
   * @param index The index of the element to return.
   * @return The paramTypes at the given index.
   */
  java.lang.String getParamTypes(int index);
  /**
   * <code>repeated string paramTypes = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the paramTypes at the given index.
   */
  com.google.protobuf.ByteString
      getParamTypesBytes(int index);

  /**
   * <code>repeated string params = 4;</code>
   * @return A list containing the params.
   */
  java.util.List<java.lang.String>
      getParamsList();
  /**
   * <code>repeated string params = 4;</code>
   * @return The count of params.
   */
  int getParamsCount();
  /**
   * <code>repeated string params = 4;</code>
   * @param index The index of the element to return.
   * @return The params at the given index.
   */
  java.lang.String getParams(int index);
  /**
   * <code>repeated string params = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the params at the given index.
   */
  com.google.protobuf.ByteString
      getParamsBytes(int index);

  /**
   * <code>string group = 5;</code>
   * @return The group.
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 5;</code>
   * @return The bytes for group.
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>string version = 6;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 6;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>.run.mone.mesh.bo.SideCarAddress address = 7;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.run.mone.mesh.bo.SideCarAddress address = 7;</code>
   * @return The address.
   */
  run.mone.mesh.bo.SideCarAddress getAddress();
  /**
   * <code>.run.mone.mesh.bo.SideCarAddress address = 7;</code>
   */
  run.mone.mesh.bo.SideCarAddressOrBuilder getAddressOrBuilder();

  /**
   * <code>string id = 8;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 8;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string app = 9;</code>
   * @return The app.
   */
  java.lang.String getApp();
  /**
   * <code>string app = 9;</code>
   * @return The bytes for app.
   */
  com.google.protobuf.ByteString
      getAppBytes();

  /**
   * <code>int64 timeout = 10;</code>
   * @return The timeout.
   */
  long getTimeout();

  /**
   * <code>string cmd = 11;</code>
   * @return The cmd.
   */
  java.lang.String getCmd();
  /**
   * <code>string cmd = 11;</code>
   * @return The bytes for cmd.
   */
  com.google.protobuf.ByteString
      getCmdBytes();

  /**
   * <code>bytes data = 12;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>string type = 13;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 13;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>int32 reqId = 14;</code>
   * @return The reqId.
   */
  int getReqId();

  /**
   * <code>map&lt;string, string&gt; attachments = 15;</code>
   */
  int getAttachmentsCount();
  /**
   * <code>map&lt;string, string&gt; attachments = 15;</code>
   */
  boolean containsAttachments(
      java.lang.String key);
  /**
   * Use {@link #getAttachmentsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAttachments();
  /**
   * <code>map&lt;string, string&gt; attachments = 15;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAttachmentsMap();
  /**
   * <code>map&lt;string, string&gt; attachments = 15;</code>
   */

  java.lang.String getAttachmentsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; attachments = 15;</code>
   */

  java.lang.String getAttachmentsOrThrow(
      java.lang.String key);
}
