apiVersion: v1
kind: Service
metadata:
  name: hera-op-srv
  namespace: ozhera-namespace
  labels:
    app: hera-operator-server
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: hera-operator-port
      port: 8998
      targetPort: hera-8998
      nodePort: 30998
  selector:
    app: hera-operator
---
apiVersion: v1
kind: Service
metadata:
  name: hera-op-nginx
  namespace: ozhera-namespace
spec:
  ports:
    - port: 80
      targetPort: 7001
      protocol: TCP
  selector:
    app-fe: hera-operator-fe
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hera-operator-deployment
  namespace: ozhera-namespace
spec:
  selector:
    matchLabels:
      app: hera-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: hera-operator
        app-fe: hera-operator-fe
    spec:
      imagePullSecrets:
      - name: mione-opensource-credential
      containers:
        - name: hera-operator
          image: herahub/opensource-pub:hera-operator-v1-release
          ports:
            - containerPort: 8998
              name: hera-8998
        - name: hera-operator-fe
          image: herahub/opensource-pub:hera-operator-fe-v1-release
          ports:
            - containerPort: 7001
              name: hera-7001
      serviceAccountName: admin-mone