export const toolbarKeys = [
  'undo',
  'redo',
  // 'brush',
  // 'eraser',
  'heading',
  'font-family',
  'font-size',
  'bold',
  'italic',
  'underline',
  'strike',
  // 'link',
  'code',
  // 'subscript',
  // 'superscript',
  // 'hr',
  'todo',
  'emoji',
  'highlight',
  'font-color',
  'bullet-list',
  'ordered-list',
  'indent-decrease',
  'indent-increase',
  // 'break',
  'align',
  'line-height',
  'image',
  // 'video',
  // 'attachment',
  'quote',
  'code-block',
  'table'
  // 'printer',
  // 'fullscreen',
  // 'ai',
]

export const fontFamily = {
  values: [
    { name: '宋体', value: 'SimSun' },
    { name: '仿宋', value: 'FangSong' },
    { name: '黑体', value: 'SimHei' },
    { name: '楷体', value: 'KaiTi' },
    { name: '微软雅黑', value: 'Microsoft YaHei' },
    { name: '方正仿宋简体_GBK', value: 'FangSong_GB2312' },
    { name: 'Arial', value: 'Arial' }
  ]
}
