apiVersion: v1
kind: Service
metadata:
  name: hera-nginx
  namespace: ozhera-namespace
spec:
  ports:
    - port: 80
      targetPort: 7001
      protocol: TCP
  selector:
    app: hera-nginx-fe
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: tpc-nginx
  namespace: ozhera-namespace
spec:
  ports:
    - port: 80
      targetPort: 7001
      protocol: TCP
  selector:
    app: tpc-nginx-fe
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: tpclogin-nginx
  namespace: ozhera-namespace
spec:
  ports:
    - port: 80
      targetPort: 7001
      protocol: TCP
  selector:
    app: tpclogin-nginx-fe
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ozhera-namespace
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: ozhera-namespace
  labels:
    k8s-app: alertmanager
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 9093
  selector:
    k8s-app: alertmanager

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: ozhera-namespace
spec:
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
  selector:
    app: prometheus
  type: LoadBalancer