/*
 * Copyright 2020 Xiaomi
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

const mockData = {
  "code": 0,
  "message": "success",
  "data": {
    page: 1,
    pageSize: 10,
    total: 20,
    list: [
      {
        "id": 1,
        "ip": null,
        "bizId": 0,
        "projectBefore": [],
        "projectAfter": [
          {
            "ip": "xx_replace_xx",
            "cpu": 0,
            "cpuCore": [
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35,
              36,
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47,
              48,
              49
            ],
            "mem": 0,
            "ports": null,
            "name": null,
            "hostName": null,
            "lables": null,
            "bizId": 0,
            "id": 1,
            "type": null,
            "remainCpu": 0,
            "systemCpu": null,
            "systemMem": 0,
            "remainMem": 0,
            "systemPorts": null,
            "owners": null,
            "loadAverage": 0.0,
            "supportKeyCenter": 0,
            "status": 0,
            "rorder": 0,
            "utime": 0
          }
        ],
        "resourceBefore": null,
        "resourceAfter": null,
        "type": "createQuota",
        "ctime": 1590118075158,
        "status": 0,
        "operator": null
      },
      {
        "id": 2,
        "ip": "xx_replace_xx",
        "bizId": 0,
        "projectBefore": [
          {
            "ip": "xx_replace_xx",
            "cpu": 0,
            "cpuCore": [
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35,
              36,
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47,
              48,
              49
            ],
            "mem": 0,
            "ports": null,
            "name": null,
            "hostName": null,
            "lables": null,
            "bizId": 0,
            "id": 1,
            "type": null,
            "remainCpu": 0,
            "systemCpu": null,
            "systemMem": 0,
            "remainMem": 0,
            "systemPorts": null,
            "owners": null,
            "loadAverage": 0.0,
            "supportKeyCenter": 0,
            "status": 0,
            "rorder": 0,
            "utime": 0
          }
        ],
        "projectAfter": [
          {
            "ip": "xx_replace_xx",
            "cpu": 0,
            "cpuCore": [
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35,
              36,
              37,
              38,
              39,
              40,
              41,
              42,
              43,
              44,
              45,
              46,
              47,
              48,
              49
            ],
            "mem": 0,
            "ports": null,
            "name": null,
            "hostName": null,
            "lables": null,
            "bizId": 0,
            "id": 2,
            "type": null,
            "remainCpu": 0,
            "systemCpu": null,
            "systemMem": 0,
            "remainMem": 0,
            "systemPorts": null,
            "owners": null,
            "loadAverage": 0.0,
            "supportKeyCenter": 0,
            "status": 0,
            "rorder": 0,
            "utime": 0
          }
        ],
        "resourceBefore": null,
        "resourceAfter": null,
        "type": "drift",
        "ctime": 1590118075252,
        "status": 0,
        "operator": null
      }
    ]
  }
}
export default mockData
