// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package run.mone.mone.ultraman.grpc;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_ParamMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_ParamMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xiaomi_mone_ultraman_grpc_UltramanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xiaomi_mone_ultraman_grpc_UltramanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xiaomi_mone_ultraman_grpc_UltramanResponse_ResMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xiaomi_mone_ultraman_grpc_UltramanResponse_ResMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {

    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_descriptor,
        new String[] { "Id", "Cmd", "Params", "ParamMap", });
    internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_ParamMapEntry_descriptor =
      internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_ParamMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_ParamMapEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_com_xiaomi_mone_ultraman_grpc_UltramanResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xiaomi_mone_ultraman_grpc_UltramanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xiaomi_mone_ultraman_grpc_UltramanResponse_descriptor,
        new String[] { "Id", "Data", "Code", "Cmd", "ResMap", });
    internal_static_com_xiaomi_mone_ultraman_grpc_UltramanResponse_ResMapEntry_descriptor =
      internal_static_com_xiaomi_mone_ultraman_grpc_UltramanResponse_descriptor.getNestedTypes().get(0);
    internal_static_com_xiaomi_mone_ultraman_grpc_UltramanResponse_ResMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xiaomi_mone_ultraman_grpc_UltramanResponse_ResMapEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
