// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package run.mone.mone.ultraman.grpc;

/**
 * Protobuf type {@code com.xiaomi.mone.ultraman.grpc.UltramanRequest}
 */
public  final class UltramanRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.xiaomi.mone.ultraman.grpc.UltramanRequest)
    UltramanRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UltramanRequest.newBuilder() to construct.
  private UltramanRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UltramanRequest() {
    id_ = "";
    cmd_ = "";
    params_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UltramanRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            cmd_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            params_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              paramMap_ = com.google.protobuf.MapField.newMapField(
                  ParamMapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000008;
            }
            com.google.protobuf.MapEntry<String, String>
            paramMap__ = input.readMessage(
                ParamMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            paramMap_.getMutableMap().put(
                paramMap__.getKey(), paramMap__.getValue());
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Service.internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 4:
        return internalGetParamMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Service.internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            UltramanRequest.class, Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile Object id_;
  /**
   * <code>string id = 1;</code>
   */
  public String getId() {
    Object ref = id_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    Object ref = id_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CMD_FIELD_NUMBER = 2;
  private volatile Object cmd_;
  /**
   * <code>string cmd = 2;</code>
   */
  public String getCmd() {
    Object ref = cmd_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      cmd_ = s;
      return s;
    }
  }
  /**
   * <code>string cmd = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCmdBytes() {
    Object ref = cmd_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      cmd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAMS_FIELD_NUMBER = 3;
  private volatile Object params_;
  /**
   * <code>string params = 3;</code>
   */
  public String getParams() {
    Object ref = params_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      params_ = s;
      return s;
    }
  }
  /**
   * <code>string params = 3;</code>
   */
  public com.google.protobuf.ByteString
      getParamsBytes() {
    Object ref = params_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      params_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAMMAP_FIELD_NUMBER = 4;
  private static final class ParamMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, String> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, String>newDefaultInstance(
                Service.internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_ParamMapEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      String, String> paramMap_;
  private com.google.protobuf.MapField<String, String>
  internalGetParamMap() {
    if (paramMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ParamMapDefaultEntryHolder.defaultEntry);
    }
    return paramMap_;
  }

  public int getParamMapCount() {
    return internalGetParamMap().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; paramMap = 4;</code>
   */

  public boolean containsParamMap(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    return internalGetParamMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getParamMapMap()} instead.
   */
  @Deprecated
  public java.util.Map<String, String> getParamMap() {
    return getParamMapMap();
  }
  /**
   * <code>map&lt;string, string&gt; paramMap = 4;</code>
   */

  public java.util.Map<String, String> getParamMapMap() {
    return internalGetParamMap().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; paramMap = 4;</code>
   */

  public String getParamMapOrDefault(
      String key,
      String defaultValue) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, String> map =
        internalGetParamMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; paramMap = 4;</code>
   */

  public String getParamMapOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, String> map =
        internalGetParamMap().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getCmdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cmd_);
    }
    if (!getParamsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, params_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetParamMap(),
        ParamMapDefaultEntryHolder.defaultEntry,
        4);
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getCmdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cmd_);
    }
    if (!getParamsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, params_);
    }
    for (java.util.Map.Entry<String, String> entry
         : internalGetParamMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, String>
      paramMap__ = ParamMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, paramMap__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof UltramanRequest)) {
      return super.equals(obj);
    }
    UltramanRequest other = (UltramanRequest) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getCmd()
        .equals(other.getCmd());
    result = result && getParams()
        .equals(other.getParams());
    result = result && internalGetParamMap().equals(
        other.internalGetParamMap());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + CMD_FIELD_NUMBER;
    hash = (53 * hash) + getCmd().hashCode();
    hash = (37 * hash) + PARAMS_FIELD_NUMBER;
    hash = (53 * hash) + getParams().hashCode();
    if (!internalGetParamMap().getMap().isEmpty()) {
      hash = (37 * hash) + PARAMMAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetParamMap().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static UltramanRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UltramanRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UltramanRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UltramanRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UltramanRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UltramanRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UltramanRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UltramanRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static UltramanRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static UltramanRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static UltramanRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UltramanRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(UltramanRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.xiaomi.mone.ultraman.grpc.UltramanRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.xiaomi.mone.ultraman.grpc.UltramanRequest)
      UltramanRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Service.internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetParamMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableParamMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Service.internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UltramanRequest.class, Builder.class);
    }

    // Construct using com.xiaomi.mone.ultraman.grpc.UltramanRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = "";

      cmd_ = "";

      params_ = "";

      internalGetMutableParamMap().clear();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Service.internal_static_com_xiaomi_mone_ultraman_grpc_UltramanRequest_descriptor;
    }

    @Override
    public UltramanRequest getDefaultInstanceForType() {
      return UltramanRequest.getDefaultInstance();
    }

    @Override
    public UltramanRequest build() {
      UltramanRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public UltramanRequest buildPartial() {
      UltramanRequest result = new UltramanRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.cmd_ = cmd_;
      result.params_ = params_;
      result.paramMap_ = internalGetParamMap();
      result.paramMap_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof UltramanRequest) {
        return mergeFrom((UltramanRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(UltramanRequest other) {
      if (other == UltramanRequest.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getCmd().isEmpty()) {
        cmd_ = other.cmd_;
        onChanged();
      }
      if (!other.getParams().isEmpty()) {
        params_ = other.params_;
        onChanged();
      }
      internalGetMutableParamMap().mergeFrom(
          other.internalGetParamMap());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      UltramanRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (UltramanRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object id_ = "";
    /**
     * <code>string id = 1;</code>
     */
    public String getId() {
      Object ref = id_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private Object cmd_ = "";
    /**
     * <code>string cmd = 2;</code>
     */
    public String getCmd() {
      Object ref = cmd_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string cmd = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCmdBytes() {
      Object ref = cmd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cmd = 2;</code>
     */
    public Builder setCmd(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cmd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cmd = 2;</code>
     */
    public Builder clearCmd() {
      
      cmd_ = getDefaultInstance().getCmd();
      onChanged();
      return this;
    }
    /**
     * <code>string cmd = 2;</code>
     */
    public Builder setCmdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cmd_ = value;
      onChanged();
      return this;
    }

    private Object params_ = "";
    /**
     * <code>string params = 3;</code>
     */
    public String getParams() {
      Object ref = params_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        params_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string params = 3;</code>
     */
    public com.google.protobuf.ByteString
        getParamsBytes() {
      Object ref = params_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        params_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string params = 3;</code>
     */
    public Builder setParams(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      params_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string params = 3;</code>
     */
    public Builder clearParams() {
      
      params_ = getDefaultInstance().getParams();
      onChanged();
      return this;
    }
    /**
     * <code>string params = 3;</code>
     */
    public Builder setParamsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      params_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        String, String> paramMap_;
    private com.google.protobuf.MapField<String, String>
    internalGetParamMap() {
      if (paramMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ParamMapDefaultEntryHolder.defaultEntry);
      }
      return paramMap_;
    }
    private com.google.protobuf.MapField<String, String>
    internalGetMutableParamMap() {
      onChanged();;
      if (paramMap_ == null) {
        paramMap_ = com.google.protobuf.MapField.newMapField(
            ParamMapDefaultEntryHolder.defaultEntry);
      }
      if (!paramMap_.isMutable()) {
        paramMap_ = paramMap_.copy();
      }
      return paramMap_;
    }

    public int getParamMapCount() {
      return internalGetParamMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; paramMap = 4;</code>
     */

    public boolean containsParamMap(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetParamMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getParamMapMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getParamMap() {
      return getParamMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; paramMap = 4;</code>
     */

    public java.util.Map<String, String> getParamMapMap() {
      return internalGetParamMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; paramMap = 4;</code>
     */

    public String getParamMapOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetParamMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; paramMap = 4;</code>
     */

    public String getParamMapOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetParamMap().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearParamMap() {
      internalGetMutableParamMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; paramMap = 4;</code>
     */

    public Builder removeParamMap(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      internalGetMutableParamMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, String>
    getMutableParamMap() {
      return internalGetMutableParamMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; paramMap = 4;</code>
     */
    public Builder putParamMap(
        String key,
        String value) {
      if (key == null) { throw new NullPointerException(); }
      if (value == null) { throw new NullPointerException(); }
      internalGetMutableParamMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; paramMap = 4;</code>
     */

    public Builder putAllParamMap(
        java.util.Map<String, String> values) {
      internalGetMutableParamMap().getMutableMap()
          .putAll(values);
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.xiaomi.mone.ultraman.grpc.UltramanRequest)
  }

  // @@protoc_insertion_point(class_scope:com.xiaomi.mone.ultraman.grpc.UltramanRequest)
  private static final UltramanRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new UltramanRequest();
  }

  public static UltramanRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UltramanRequest>
      PARSER = new com.google.protobuf.AbstractParser<UltramanRequest>() {
    @Override
    public UltramanRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UltramanRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UltramanRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<UltramanRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public UltramanRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

