// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package run.mone.mone.ultraman.grpc;

public interface UltramanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xiaomi.mone.ultraman.grpc.UltramanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string data = 2;</code>
   */
  String getData();
  /**
   * <code>string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <code>int32 code = 3;</code>
   */
  int getCode();

  /**
   * <code>string cmd = 4;</code>
   */
  String getCmd();
  /**
   * <code>string cmd = 4;</code>
   */
  com.google.protobuf.ByteString
      getCmdBytes();

  /**
   * <code>map&lt;string, string&gt; resMap = 5;</code>
   */
  int getResMapCount();
  /**
   * <code>map&lt;string, string&gt; resMap = 5;</code>
   */
  boolean containsResMap(
      String key);
  /**
   * Use {@link #getResMapMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getResMap();
  /**
   * <code>map&lt;string, string&gt; resMap = 5;</code>
   */
  java.util.Map<String, String>
  getResMapMap();
  /**
   * <code>map&lt;string, string&gt; resMap = 5;</code>
   */

  String getResMapOrDefault(
      String key,
      String defaultValue);
  /**
   * <code>map&lt;string, string&gt; resMap = 5;</code>
   */

  String getResMapOrThrow(
      String key);
}
