apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimonitor
  namespace: ozhera-namespace
  labels:
    app: mimonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimonitor
  template:
    metadata:
      labels:
        app: mimonitor
    spec:
      containers:
      - name: mimonitor-container
        image: herahub/opensource-pub:mimonitor-v1-release
        resources:
          limits:
            cpu: '500m'
            memory: 2Gi
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 8099
          initialDelaySeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: mimonitor
  namespace: ozhera-namespace
  labels:
    app: mimonitor
spec:
  ports:
    - port: 8099
      targetPort: 8099
      protocol: TCP
  selector:
    app: mimonitor
  clusterIP: None
