codecov:
  notify:
    require_ci_to_pass: yes
  strict_yaml_branch: main  # only use the latest copy on main branch

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        enabled: yes
        target: 90%
        paths:
          - api
          - sdk
    patch:
      default:
        enabled: yes
        target: 90%
        paths:
          - api
          - sdk
