memory:
  # LLM Configuration
  llm:
    providerName: QWEN

  # Embedder Configuration
  embedder:
    provider: ollama
    model: embeddinggemma
    embeddingDims: 768

  # Vector Store Configuration
  vectorStore:
    provider: chroma
    port: 8000
    collectionName: test_collection1
    embeddingModelDims: 768
    embeddingFunction: ollama

  # Graph Store Configuration
  graphStore:
    provider: neo4j
    enabled: true
    url: bolt://localhost:7687
    # url will be set programmatically to temp directory
    llm:
      providerName: QWEN
    embedder:
      provider: ollama
      model: embeddinggemma
      embeddingDims: 768

  # History Database Path
  historyDbPath: ./temp/history.db

  # API Version
  version: v1.1