FROM openjdk:8-jre

COPY ./hera-monitor-server/target/hera-monitor-server-1.1-SNAPSHOT.jar /home/work/hera-monitor-server-1.1-SNAPSHOT.jar

ENTRYPOINT ["java","-XX:+PrintReferenceGC","-XX:+PrintGCDetails","-XX:+PrintGCDateStamps","-XX:+PrintHeapAtGC","-Xloggc:/home/work/log/gc.log","-Duser.timezone=Asia/Shanghai","-XX:+HeapDumpOnOutOfMemoryError","-XX:HeapDumpPath=/home/rocksdb/dum/oom.dump","-jar","/home/work/hera-monitor-server-1.1-SNAPSHOT.jar","&&","tail","-f","/dev/null"]
