apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-etl-manager
  namespace: hera-namespace
  labels:
    app: trace-etl-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trace-etl-manager
  template:
    metadata:
      labels:
        app: trace-etl-manager
    spec:
      containers:
      - name: trace-etl-manager-container
        image: prod-mione-opensource-registry.cn-beijing.cr.aliyuncs.com/prod-mione-opensource/prod-mione-opensource:trace-etl-manager-v5
        resources:
          limits:
            cpu: '500m'
            memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: trace-etl-manager
  namespace: hera-namespace
  labels:
    app: trace-etl-manager
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: trace-etl-manager
  clusterIP: None
