apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-tpc
  namespace: hera-namespace
  labels:
    app: mi-tpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-tpc
  template:
    metadata:
      labels:
        app: mi-tpc
    spec:
      containers:
      - name: mi-tpc-container
        image: prod-mione-opensource-registry.cn-beijing.cr.aliyuncs.com/prod-mione-opensource/prod-mione-opensource:mi-tpc-v27
        resources:
          limits:
            cpu: '500m'
            memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mi-tpc
  namespace: hera-namespace
  labels:
    app: mi-tpc-service
spec:
  ports:
    - port: 8097
      targetPort: 8097
      protocol: TCP
  selector:
    app: mi-tpc
  clusterIP: None