// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.xiaomi.mone.grpc.demo;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xiaomi.mone.grpc.demo.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstName = 1;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 1;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 2;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 2;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
