// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.xiaomi.mone.grpc.demo;

public interface MeshAddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xiaomi.mone.grpc.demo.MeshAddress)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 1;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int32 port = 2;</code>
   * @return The port.
   */
  int getPort();
}
