apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: ozhera-namespace
  labels:
    name: redis
spec:
  ports:
    - port: 6379
      protocol: TCP
  selector:
    name: redis
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: ozhera-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP