apiVersion: v1
kind: Service
metadata:
  name: m78
  namespace: infra
  labels:
    k8s-app: m78-server
spec:
  ports:
    - name: http
      port: 8076
      targetPort: 8076
    - name: rpc
      port: 7678
      targetPort: 7678
  selector:
    k8s-app: m78-server

---

apiVersion: v1
kind: Service
metadata:
  name: m78-lb
  namespace: infra
spec:
  ports:
    - port: 80
      targetPort: 8076
      protocol: TCP
  selector:
    k8s-app: m78-server
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: m78-server-deploy
  namespace: infra
  labels:
    k8s-app: m78-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: m78-server
  template:
    metadata:
      labels:
        k8s-app: m78-server
    spec:
      containers:
        - name: main-m78-server
          image: test.com/m78:oz-m78-v1
          env:
            - name: LANG
              value: C.UTF-8
            - name: TZ
              value: Asia/Shanghai
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
