// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bo.proto

package run.mone.local.docean.protobuf;

/**
 * Protobuf type {@code run.mone.local.docean.protobuf.DatumMapData}
 */
public final class DatumMapData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:run.mone.local.docean.protobuf.DatumMapData)
    DatumMapDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DatumMapData.newBuilder() to construct.
  private DatumMapData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DatumMapData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DatumMapData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DatumMapData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              datumMap_ = com.google.protobuf.MapField.newMapField(
                  DatumMapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, run.mone.local.docean.protobuf.InstancesProto>
            datumMap__ = input.readMessage(
                DatumMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            datumMap_.getMutableMap().put(
                datumMap__.getKey(), datumMap__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return run.mone.local.docean.protobuf.Bo.internal_static_run_mone_local_docean_protobuf_DatumMapData_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetDatumMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return run.mone.local.docean.protobuf.Bo.internal_static_run_mone_local_docean_protobuf_DatumMapData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            run.mone.local.docean.protobuf.DatumMapData.class, run.mone.local.docean.protobuf.DatumMapData.Builder.class);
  }

  public static final int DATUMMAP_FIELD_NUMBER = 1;
  private static final class DatumMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, run.mone.local.docean.protobuf.InstancesProto> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, run.mone.local.docean.protobuf.InstancesProto>newDefaultInstance(
                run.mone.local.docean.protobuf.Bo.internal_static_run_mone_local_docean_protobuf_DatumMapData_DatumMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                run.mone.local.docean.protobuf.InstancesProto.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, run.mone.local.docean.protobuf.InstancesProto> datumMap_;
  private com.google.protobuf.MapField<java.lang.String, run.mone.local.docean.protobuf.InstancesProto>
  internalGetDatumMap() {
    if (datumMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          DatumMapDefaultEntryHolder.defaultEntry);
    }
    return datumMap_;
  }

  public int getDatumMapCount() {
    return internalGetDatumMap().getMap().size();
  }
  /**
   * <code>map&lt;string, .run.mone.local.docean.protobuf.InstancesProto&gt; datumMap = 1;</code>
   */

  @java.lang.Override
  public boolean containsDatumMap(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetDatumMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getDatumMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, run.mone.local.docean.protobuf.InstancesProto> getDatumMap() {
    return getDatumMapMap();
  }
  /**
   * <code>map&lt;string, .run.mone.local.docean.protobuf.InstancesProto&gt; datumMap = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, run.mone.local.docean.protobuf.InstancesProto> getDatumMapMap() {
    return internalGetDatumMap().getMap();
  }
  /**
   * <code>map&lt;string, .run.mone.local.docean.protobuf.InstancesProto&gt; datumMap = 1;</code>
   */
  @java.lang.Override

  public run.mone.local.docean.protobuf.InstancesProto getDatumMapOrDefault(
      java.lang.String key,
      run.mone.local.docean.protobuf.InstancesProto defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, run.mone.local.docean.protobuf.InstancesProto> map =
        internalGetDatumMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .run.mone.local.docean.protobuf.InstancesProto&gt; datumMap = 1;</code>
   */
  @java.lang.Override

  public run.mone.local.docean.protobuf.InstancesProto getDatumMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, run.mone.local.docean.protobuf.InstancesProto> map =
        internalGetDatumMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetDatumMap(),
        DatumMapDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, run.mone.local.docean.protobuf.InstancesProto> entry
         : internalGetDatumMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, run.mone.local.docean.protobuf.InstancesProto>
      datumMap__ = DatumMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, datumMap__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof run.mone.local.docean.protobuf.DatumMapData)) {
      return super.equals(obj);
    }
    run.mone.local.docean.protobuf.DatumMapData other = (run.mone.local.docean.protobuf.DatumMapData) obj;

    if (!internalGetDatumMap().equals(
        other.internalGetDatumMap())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetDatumMap().getMap().isEmpty()) {
      hash = (37 * hash) + DATUMMAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetDatumMap().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static run.mone.local.docean.protobuf.DatumMapData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static run.mone.local.docean.protobuf.DatumMapData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static run.mone.local.docean.protobuf.DatumMapData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static run.mone.local.docean.protobuf.DatumMapData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static run.mone.local.docean.protobuf.DatumMapData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static run.mone.local.docean.protobuf.DatumMapData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static run.mone.local.docean.protobuf.DatumMapData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static run.mone.local.docean.protobuf.DatumMapData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static run.mone.local.docean.protobuf.DatumMapData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static run.mone.local.docean.protobuf.DatumMapData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static run.mone.local.docean.protobuf.DatumMapData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static run.mone.local.docean.protobuf.DatumMapData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(run.mone.local.docean.protobuf.DatumMapData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code run.mone.local.docean.protobuf.DatumMapData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:run.mone.local.docean.protobuf.DatumMapData)
      run.mone.local.docean.protobuf.DatumMapDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return run.mone.local.docean.protobuf.Bo.internal_static_run_mone_local_docean_protobuf_DatumMapData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetDatumMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableDatumMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return run.mone.local.docean.protobuf.Bo.internal_static_run_mone_local_docean_protobuf_DatumMapData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              run.mone.local.docean.protobuf.DatumMapData.class, run.mone.local.docean.protobuf.DatumMapData.Builder.class);
    }

    // Construct using run.mone.local.docean.protobuf.DatumMapData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableDatumMap().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return run.mone.local.docean.protobuf.Bo.internal_static_run_mone_local_docean_protobuf_DatumMapData_descriptor;
    }

    @java.lang.Override
    public run.mone.local.docean.protobuf.DatumMapData getDefaultInstanceForType() {
      return run.mone.local.docean.protobuf.DatumMapData.getDefaultInstance();
    }

    @java.lang.Override
    public run.mone.local.docean.protobuf.DatumMapData build() {
      run.mone.local.docean.protobuf.DatumMapData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public run.mone.local.docean.protobuf.DatumMapData buildPartial() {
      run.mone.local.docean.protobuf.DatumMapData result = new run.mone.local.docean.protobuf.DatumMapData(this);
      int from_bitField0_ = bitField0_;
      result.datumMap_ = internalGetDatumMap();
      result.datumMap_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof run.mone.local.docean.protobuf.DatumMapData) {
        return mergeFrom((run.mone.local.docean.protobuf.DatumMapData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(run.mone.local.docean.protobuf.DatumMapData other) {
      if (other == run.mone.local.docean.protobuf.DatumMapData.getDefaultInstance()) return this;
      internalGetMutableDatumMap().mergeFrom(
          other.internalGetDatumMap());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      run.mone.local.docean.protobuf.DatumMapData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (run.mone.local.docean.protobuf.DatumMapData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, run.mone.local.docean.protobuf.InstancesProto> datumMap_;
    private com.google.protobuf.MapField<java.lang.String, run.mone.local.docean.protobuf.InstancesProto>
    internalGetDatumMap() {
      if (datumMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DatumMapDefaultEntryHolder.defaultEntry);
      }
      return datumMap_;
    }
    private com.google.protobuf.MapField<java.lang.String, run.mone.local.docean.protobuf.InstancesProto>
    internalGetMutableDatumMap() {
      onChanged();;
      if (datumMap_ == null) {
        datumMap_ = com.google.protobuf.MapField.newMapField(
            DatumMapDefaultEntryHolder.defaultEntry);
      }
      if (!datumMap_.isMutable()) {
        datumMap_ = datumMap_.copy();
      }
      return datumMap_;
    }

    public int getDatumMapCount() {
      return internalGetDatumMap().getMap().size();
    }
    /**
     * <code>map&lt;string, .run.mone.local.docean.protobuf.InstancesProto&gt; datumMap = 1;</code>
     */

    @java.lang.Override
    public boolean containsDatumMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetDatumMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDatumMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, run.mone.local.docean.protobuf.InstancesProto> getDatumMap() {
      return getDatumMapMap();
    }
    /**
     * <code>map&lt;string, .run.mone.local.docean.protobuf.InstancesProto&gt; datumMap = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, run.mone.local.docean.protobuf.InstancesProto> getDatumMapMap() {
      return internalGetDatumMap().getMap();
    }
    /**
     * <code>map&lt;string, .run.mone.local.docean.protobuf.InstancesProto&gt; datumMap = 1;</code>
     */
    @java.lang.Override

    public run.mone.local.docean.protobuf.InstancesProto getDatumMapOrDefault(
        java.lang.String key,
        run.mone.local.docean.protobuf.InstancesProto defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, run.mone.local.docean.protobuf.InstancesProto> map =
          internalGetDatumMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .run.mone.local.docean.protobuf.InstancesProto&gt; datumMap = 1;</code>
     */
    @java.lang.Override

    public run.mone.local.docean.protobuf.InstancesProto getDatumMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, run.mone.local.docean.protobuf.InstancesProto> map =
          internalGetDatumMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearDatumMap() {
      internalGetMutableDatumMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .run.mone.local.docean.protobuf.InstancesProto&gt; datumMap = 1;</code>
     */

    public Builder removeDatumMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableDatumMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, run.mone.local.docean.protobuf.InstancesProto>
    getMutableDatumMap() {
      return internalGetMutableDatumMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, .run.mone.local.docean.protobuf.InstancesProto&gt; datumMap = 1;</code>
     */
    public Builder putDatumMap(
        java.lang.String key,
        run.mone.local.docean.protobuf.InstancesProto value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableDatumMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .run.mone.local.docean.protobuf.InstancesProto&gt; datumMap = 1;</code>
     */

    public Builder putAllDatumMap(
        java.util.Map<java.lang.String, run.mone.local.docean.protobuf.InstancesProto> values) {
      internalGetMutableDatumMap().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:run.mone.local.docean.protobuf.DatumMapData)
  }

  // @@protoc_insertion_point(class_scope:run.mone.local.docean.protobuf.DatumMapData)
  private static final run.mone.local.docean.protobuf.DatumMapData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new run.mone.local.docean.protobuf.DatumMapData();
  }

  public static run.mone.local.docean.protobuf.DatumMapData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DatumMapData>
      PARSER = new com.google.protobuf.AbstractParser<DatumMapData>() {
    @java.lang.Override
    public DatumMapData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DatumMapData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DatumMapData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DatumMapData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public run.mone.local.docean.protobuf.DatumMapData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

