// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bo.proto

package run.mone.local.docean.protobuf;

/**
 * Protobuf type {@code run.mone.local.docean.protobuf.ListRequest}
 */
public final class ListRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:run.mone.local.docean.protobuf.ListRequest)
    ListRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListRequest.newBuilder() to construct.
  private ListRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListRequest() {
    namespaceId_ = "";
    serviceName_ = "";
    agent_ = "";
    clusters_ = "";
    clientIP_ = "";
    env_ = "";
    app_ = "";
    tid_ = "";
    tenant_ = "";
    cmd_ = "";
    cluster_ = "";
    ip_ = "";
    groupName_ = "";
    selectorString_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            namespaceId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            serviceName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            agent_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            clusters_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            clientIP_ = s;
            break;
          }
          case 48: {

            udpPort_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            env_ = s;
            break;
          }
          case 64: {

            isCheck_ = input.readBool();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            app_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            tid_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            tenant_ = s;
            break;
          }
          case 96: {

            healthyOnly_ = input.readBool();
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            cmd_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            cluster_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            ip_ = s;
            break;
          }
          case 128: {

            port_ = input.readInt32();
            break;
          }
          case 136: {

            pageNo_ = input.readInt32();
            break;
          }
          case 144: {

            pageSize_ = input.readInt32();
            break;
          }
          case 154: {
            java.lang.String s = input.readStringRequireUtf8();

            groupName_ = s;
            break;
          }
          case 162: {
            java.lang.String s = input.readStringRequireUtf8();

            selectorString_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return run.mone.local.docean.protobuf.Bo.internal_static_run_mone_local_docean_protobuf_ListRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return run.mone.local.docean.protobuf.Bo.internal_static_run_mone_local_docean_protobuf_ListRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            run.mone.local.docean.protobuf.ListRequest.class, run.mone.local.docean.protobuf.ListRequest.Builder.class);
  }

  public static final int NAMESPACEID_FIELD_NUMBER = 1;
  private volatile java.lang.Object namespaceId_;
  /**
   * <pre>
   *list
   * </pre>
   *
   * <code>string namespaceId = 1;</code>
   * @return The namespaceId.
   */
  @java.lang.Override
  public java.lang.String getNamespaceId() {
    java.lang.Object ref = namespaceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      namespaceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *list
   * </pre>
   *
   * <code>string namespaceId = 1;</code>
   * @return The bytes for namespaceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNamespaceIdBytes() {
    java.lang.Object ref = namespaceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      namespaceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object serviceName_;
  /**
   * <code>string serviceName = 2;</code>
   * @return The serviceName.
   */
  @java.lang.Override
  public java.lang.String getServiceName() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceName_ = s;
      return s;
    }
  }
  /**
   * <code>string serviceName = 2;</code>
   * @return The bytes for serviceName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceNameBytes() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGENT_FIELD_NUMBER = 3;
  private volatile java.lang.Object agent_;
  /**
   * <code>string agent = 3;</code>
   * @return The agent.
   */
  @java.lang.Override
  public java.lang.String getAgent() {
    java.lang.Object ref = agent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      agent_ = s;
      return s;
    }
  }
  /**
   * <code>string agent = 3;</code>
   * @return The bytes for agent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAgentBytes() {
    java.lang.Object ref = agent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      agent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLUSTERS_FIELD_NUMBER = 4;
  private volatile java.lang.Object clusters_;
  /**
   * <code>string clusters = 4;</code>
   * @return The clusters.
   */
  @java.lang.Override
  public java.lang.String getClusters() {
    java.lang.Object ref = clusters_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clusters_ = s;
      return s;
    }
  }
  /**
   * <code>string clusters = 4;</code>
   * @return The bytes for clusters.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClustersBytes() {
    java.lang.Object ref = clusters_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clusters_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENTIP_FIELD_NUMBER = 5;
  private volatile java.lang.Object clientIP_;
  /**
   * <code>string clientIP = 5;</code>
   * @return The clientIP.
   */
  @java.lang.Override
  public java.lang.String getClientIP() {
    java.lang.Object ref = clientIP_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientIP_ = s;
      return s;
    }
  }
  /**
   * <code>string clientIP = 5;</code>
   * @return The bytes for clientIP.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientIPBytes() {
    java.lang.Object ref = clientIP_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientIP_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UDPPORT_FIELD_NUMBER = 6;
  private int udpPort_;
  /**
   * <code>int32 udpPort = 6;</code>
   * @return The udpPort.
   */
  @java.lang.Override
  public int getUdpPort() {
    return udpPort_;
  }

  public static final int ENV_FIELD_NUMBER = 7;
  private volatile java.lang.Object env_;
  /**
   * <code>string env = 7;</code>
   * @return The env.
   */
  @java.lang.Override
  public java.lang.String getEnv() {
    java.lang.Object ref = env_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      env_ = s;
      return s;
    }
  }
  /**
   * <code>string env = 7;</code>
   * @return The bytes for env.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEnvBytes() {
    java.lang.Object ref = env_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      env_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISCHECK_FIELD_NUMBER = 8;
  private boolean isCheck_;
  /**
   * <code>bool isCheck = 8;</code>
   * @return The isCheck.
   */
  @java.lang.Override
  public boolean getIsCheck() {
    return isCheck_;
  }

  public static final int APP_FIELD_NUMBER = 9;
  private volatile java.lang.Object app_;
  /**
   * <code>string app = 9;</code>
   * @return The app.
   */
  @java.lang.Override
  public java.lang.String getApp() {
    java.lang.Object ref = app_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      app_ = s;
      return s;
    }
  }
  /**
   * <code>string app = 9;</code>
   * @return The bytes for app.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppBytes() {
    java.lang.Object ref = app_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      app_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TID_FIELD_NUMBER = 10;
  private volatile java.lang.Object tid_;
  /**
   * <code>string tid = 10;</code>
   * @return The tid.
   */
  @java.lang.Override
  public java.lang.String getTid() {
    java.lang.Object ref = tid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tid_ = s;
      return s;
    }
  }
  /**
   * <code>string tid = 10;</code>
   * @return The bytes for tid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTidBytes() {
    java.lang.Object ref = tid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANT_FIELD_NUMBER = 11;
  private volatile java.lang.Object tenant_;
  /**
   * <code>string tenant = 11;</code>
   * @return The tenant.
   */
  @java.lang.Override
  public java.lang.String getTenant() {
    java.lang.Object ref = tenant_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenant_ = s;
      return s;
    }
  }
  /**
   * <code>string tenant = 11;</code>
   * @return The bytes for tenant.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantBytes() {
    java.lang.Object ref = tenant_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenant_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEALTHYONLY_FIELD_NUMBER = 12;
  private boolean healthyOnly_;
  /**
   * <code>bool healthyOnly = 12;</code>
   * @return The healthyOnly.
   */
  @java.lang.Override
  public boolean getHealthyOnly() {
    return healthyOnly_;
  }

  public static final int CMD_FIELD_NUMBER = 13;
  private volatile java.lang.Object cmd_;
  /**
   * <code>string cmd = 13;</code>
   * @return The cmd.
   */
  @java.lang.Override
  public java.lang.String getCmd() {
    java.lang.Object ref = cmd_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cmd_ = s;
      return s;
    }
  }
  /**
   * <code>string cmd = 13;</code>
   * @return The bytes for cmd.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCmdBytes() {
    java.lang.Object ref = cmd_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cmd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLUSTER_FIELD_NUMBER = 14;
  private volatile java.lang.Object cluster_;
  /**
   * <pre>
   *detail
   * </pre>
   *
   * <code>string cluster = 14;</code>
   * @return The cluster.
   */
  @java.lang.Override
  public java.lang.String getCluster() {
    java.lang.Object ref = cluster_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cluster_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *detail
   * </pre>
   *
   * <code>string cluster = 14;</code>
   * @return The bytes for cluster.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClusterBytes() {
    java.lang.Object ref = cluster_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cluster_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IP_FIELD_NUMBER = 15;
  private volatile java.lang.Object ip_;
  /**
   * <code>string ip = 15;</code>
   * @return The ip.
   */
  @java.lang.Override
  public java.lang.String getIp() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ip_ = s;
      return s;
    }
  }
  /**
   * <code>string ip = 15;</code>
   * @return The bytes for ip.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIpBytes() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORT_FIELD_NUMBER = 16;
  private int port_;
  /**
   * <code>int32 port = 16;</code>
   * @return The port.
   */
  @java.lang.Override
  public int getPort() {
    return port_;
  }

  public static final int PAGENO_FIELD_NUMBER = 17;
  private int pageNo_;
  /**
   * <pre>
   *list_service
   * </pre>
   *
   * <code>int32 pageNo = 17;</code>
   * @return The pageNo.
   */
  @java.lang.Override
  public int getPageNo() {
    return pageNo_;
  }

  public static final int PAGESIZE_FIELD_NUMBER = 18;
  private int pageSize_;
  /**
   * <code>int32 pageSize = 18;</code>
   * @return The pageSize.
   */
  @java.lang.Override
  public int getPageSize() {
    return pageSize_;
  }

  public static final int GROUPNAME_FIELD_NUMBER = 19;
  private volatile java.lang.Object groupName_;
  /**
   * <code>string groupName = 19;</code>
   * @return The groupName.
   */
  @java.lang.Override
  public java.lang.String getGroupName() {
    java.lang.Object ref = groupName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groupName_ = s;
      return s;
    }
  }
  /**
   * <code>string groupName = 19;</code>
   * @return The bytes for groupName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupNameBytes() {
    java.lang.Object ref = groupName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groupName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SELECTORSTRING_FIELD_NUMBER = 20;
  private volatile java.lang.Object selectorString_;
  /**
   * <code>string selectorString = 20;</code>
   * @return The selectorString.
   */
  @java.lang.Override
  public java.lang.String getSelectorString() {
    java.lang.Object ref = selectorString_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      selectorString_ = s;
      return s;
    }
  }
  /**
   * <code>string selectorString = 20;</code>
   * @return The bytes for selectorString.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSelectorStringBytes() {
    java.lang.Object ref = selectorString_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      selectorString_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(namespaceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, namespaceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serviceName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(agent_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, agent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clusters_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, clusters_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientIP_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, clientIP_);
    }
    if (udpPort_ != 0) {
      output.writeInt32(6, udpPort_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(env_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, env_);
    }
    if (isCheck_ != false) {
      output.writeBool(8, isCheck_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(app_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, app_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, tid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenant_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, tenant_);
    }
    if (healthyOnly_ != false) {
      output.writeBool(12, healthyOnly_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cmd_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, cmd_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cluster_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, cluster_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ip_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, ip_);
    }
    if (port_ != 0) {
      output.writeInt32(16, port_);
    }
    if (pageNo_ != 0) {
      output.writeInt32(17, pageNo_);
    }
    if (pageSize_ != 0) {
      output.writeInt32(18, pageSize_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(groupName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 19, groupName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(selectorString_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 20, selectorString_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(namespaceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, namespaceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serviceName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(agent_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, agent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clusters_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, clusters_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientIP_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, clientIP_);
    }
    if (udpPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, udpPort_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(env_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, env_);
    }
    if (isCheck_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, isCheck_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(app_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, app_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, tid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenant_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, tenant_);
    }
    if (healthyOnly_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(12, healthyOnly_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cmd_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, cmd_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cluster_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, cluster_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ip_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, ip_);
    }
    if (port_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, port_);
    }
    if (pageNo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(17, pageNo_);
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(18, pageSize_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(groupName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, groupName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(selectorString_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, selectorString_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof run.mone.local.docean.protobuf.ListRequest)) {
      return super.equals(obj);
    }
    run.mone.local.docean.protobuf.ListRequest other = (run.mone.local.docean.protobuf.ListRequest) obj;

    if (!getNamespaceId()
        .equals(other.getNamespaceId())) return false;
    if (!getServiceName()
        .equals(other.getServiceName())) return false;
    if (!getAgent()
        .equals(other.getAgent())) return false;
    if (!getClusters()
        .equals(other.getClusters())) return false;
    if (!getClientIP()
        .equals(other.getClientIP())) return false;
    if (getUdpPort()
        != other.getUdpPort()) return false;
    if (!getEnv()
        .equals(other.getEnv())) return false;
    if (getIsCheck()
        != other.getIsCheck()) return false;
    if (!getApp()
        .equals(other.getApp())) return false;
    if (!getTid()
        .equals(other.getTid())) return false;
    if (!getTenant()
        .equals(other.getTenant())) return false;
    if (getHealthyOnly()
        != other.getHealthyOnly()) return false;
    if (!getCmd()
        .equals(other.getCmd())) return false;
    if (!getCluster()
        .equals(other.getCluster())) return false;
    if (!getIp()
        .equals(other.getIp())) return false;
    if (getPort()
        != other.getPort()) return false;
    if (getPageNo()
        != other.getPageNo()) return false;
    if (getPageSize()
        != other.getPageSize()) return false;
    if (!getGroupName()
        .equals(other.getGroupName())) return false;
    if (!getSelectorString()
        .equals(other.getSelectorString())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAMESPACEID_FIELD_NUMBER;
    hash = (53 * hash) + getNamespaceId().hashCode();
    hash = (37 * hash) + SERVICENAME_FIELD_NUMBER;
    hash = (53 * hash) + getServiceName().hashCode();
    hash = (37 * hash) + AGENT_FIELD_NUMBER;
    hash = (53 * hash) + getAgent().hashCode();
    hash = (37 * hash) + CLUSTERS_FIELD_NUMBER;
    hash = (53 * hash) + getClusters().hashCode();
    hash = (37 * hash) + CLIENTIP_FIELD_NUMBER;
    hash = (53 * hash) + getClientIP().hashCode();
    hash = (37 * hash) + UDPPORT_FIELD_NUMBER;
    hash = (53 * hash) + getUdpPort();
    hash = (37 * hash) + ENV_FIELD_NUMBER;
    hash = (53 * hash) + getEnv().hashCode();
    hash = (37 * hash) + ISCHECK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsCheck());
    hash = (37 * hash) + APP_FIELD_NUMBER;
    hash = (53 * hash) + getApp().hashCode();
    hash = (37 * hash) + TID_FIELD_NUMBER;
    hash = (53 * hash) + getTid().hashCode();
    hash = (37 * hash) + TENANT_FIELD_NUMBER;
    hash = (53 * hash) + getTenant().hashCode();
    hash = (37 * hash) + HEALTHYONLY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHealthyOnly());
    hash = (37 * hash) + CMD_FIELD_NUMBER;
    hash = (53 * hash) + getCmd().hashCode();
    hash = (37 * hash) + CLUSTER_FIELD_NUMBER;
    hash = (53 * hash) + getCluster().hashCode();
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIp().hashCode();
    hash = (37 * hash) + PORT_FIELD_NUMBER;
    hash = (53 * hash) + getPort();
    hash = (37 * hash) + PAGENO_FIELD_NUMBER;
    hash = (53 * hash) + getPageNo();
    hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPageSize();
    hash = (37 * hash) + GROUPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getGroupName().hashCode();
    hash = (37 * hash) + SELECTORSTRING_FIELD_NUMBER;
    hash = (53 * hash) + getSelectorString().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static run.mone.local.docean.protobuf.ListRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static run.mone.local.docean.protobuf.ListRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static run.mone.local.docean.protobuf.ListRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static run.mone.local.docean.protobuf.ListRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static run.mone.local.docean.protobuf.ListRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static run.mone.local.docean.protobuf.ListRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static run.mone.local.docean.protobuf.ListRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static run.mone.local.docean.protobuf.ListRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static run.mone.local.docean.protobuf.ListRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static run.mone.local.docean.protobuf.ListRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static run.mone.local.docean.protobuf.ListRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static run.mone.local.docean.protobuf.ListRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(run.mone.local.docean.protobuf.ListRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code run.mone.local.docean.protobuf.ListRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:run.mone.local.docean.protobuf.ListRequest)
      run.mone.local.docean.protobuf.ListRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return run.mone.local.docean.protobuf.Bo.internal_static_run_mone_local_docean_protobuf_ListRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return run.mone.local.docean.protobuf.Bo.internal_static_run_mone_local_docean_protobuf_ListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              run.mone.local.docean.protobuf.ListRequest.class, run.mone.local.docean.protobuf.ListRequest.Builder.class);
    }

    // Construct using run.mone.local.docean.protobuf.ListRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      namespaceId_ = "";

      serviceName_ = "";

      agent_ = "";

      clusters_ = "";

      clientIP_ = "";

      udpPort_ = 0;

      env_ = "";

      isCheck_ = false;

      app_ = "";

      tid_ = "";

      tenant_ = "";

      healthyOnly_ = false;

      cmd_ = "";

      cluster_ = "";

      ip_ = "";

      port_ = 0;

      pageNo_ = 0;

      pageSize_ = 0;

      groupName_ = "";

      selectorString_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return run.mone.local.docean.protobuf.Bo.internal_static_run_mone_local_docean_protobuf_ListRequest_descriptor;
    }

    @java.lang.Override
    public run.mone.local.docean.protobuf.ListRequest getDefaultInstanceForType() {
      return run.mone.local.docean.protobuf.ListRequest.getDefaultInstance();
    }

    @java.lang.Override
    public run.mone.local.docean.protobuf.ListRequest build() {
      run.mone.local.docean.protobuf.ListRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public run.mone.local.docean.protobuf.ListRequest buildPartial() {
      run.mone.local.docean.protobuf.ListRequest result = new run.mone.local.docean.protobuf.ListRequest(this);
      result.namespaceId_ = namespaceId_;
      result.serviceName_ = serviceName_;
      result.agent_ = agent_;
      result.clusters_ = clusters_;
      result.clientIP_ = clientIP_;
      result.udpPort_ = udpPort_;
      result.env_ = env_;
      result.isCheck_ = isCheck_;
      result.app_ = app_;
      result.tid_ = tid_;
      result.tenant_ = tenant_;
      result.healthyOnly_ = healthyOnly_;
      result.cmd_ = cmd_;
      result.cluster_ = cluster_;
      result.ip_ = ip_;
      result.port_ = port_;
      result.pageNo_ = pageNo_;
      result.pageSize_ = pageSize_;
      result.groupName_ = groupName_;
      result.selectorString_ = selectorString_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof run.mone.local.docean.protobuf.ListRequest) {
        return mergeFrom((run.mone.local.docean.protobuf.ListRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(run.mone.local.docean.protobuf.ListRequest other) {
      if (other == run.mone.local.docean.protobuf.ListRequest.getDefaultInstance()) return this;
      if (!other.getNamespaceId().isEmpty()) {
        namespaceId_ = other.namespaceId_;
        onChanged();
      }
      if (!other.getServiceName().isEmpty()) {
        serviceName_ = other.serviceName_;
        onChanged();
      }
      if (!other.getAgent().isEmpty()) {
        agent_ = other.agent_;
        onChanged();
      }
      if (!other.getClusters().isEmpty()) {
        clusters_ = other.clusters_;
        onChanged();
      }
      if (!other.getClientIP().isEmpty()) {
        clientIP_ = other.clientIP_;
        onChanged();
      }
      if (other.getUdpPort() != 0) {
        setUdpPort(other.getUdpPort());
      }
      if (!other.getEnv().isEmpty()) {
        env_ = other.env_;
        onChanged();
      }
      if (other.getIsCheck() != false) {
        setIsCheck(other.getIsCheck());
      }
      if (!other.getApp().isEmpty()) {
        app_ = other.app_;
        onChanged();
      }
      if (!other.getTid().isEmpty()) {
        tid_ = other.tid_;
        onChanged();
      }
      if (!other.getTenant().isEmpty()) {
        tenant_ = other.tenant_;
        onChanged();
      }
      if (other.getHealthyOnly() != false) {
        setHealthyOnly(other.getHealthyOnly());
      }
      if (!other.getCmd().isEmpty()) {
        cmd_ = other.cmd_;
        onChanged();
      }
      if (!other.getCluster().isEmpty()) {
        cluster_ = other.cluster_;
        onChanged();
      }
      if (!other.getIp().isEmpty()) {
        ip_ = other.ip_;
        onChanged();
      }
      if (other.getPort() != 0) {
        setPort(other.getPort());
      }
      if (other.getPageNo() != 0) {
        setPageNo(other.getPageNo());
      }
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      if (!other.getGroupName().isEmpty()) {
        groupName_ = other.groupName_;
        onChanged();
      }
      if (!other.getSelectorString().isEmpty()) {
        selectorString_ = other.selectorString_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      run.mone.local.docean.protobuf.ListRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (run.mone.local.docean.protobuf.ListRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object namespaceId_ = "";
    /**
     * <pre>
     *list
     * </pre>
     *
     * <code>string namespaceId = 1;</code>
     * @return The namespaceId.
     */
    public java.lang.String getNamespaceId() {
      java.lang.Object ref = namespaceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namespaceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *list
     * </pre>
     *
     * <code>string namespaceId = 1;</code>
     * @return The bytes for namespaceId.
     */
    public com.google.protobuf.ByteString
        getNamespaceIdBytes() {
      java.lang.Object ref = namespaceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namespaceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *list
     * </pre>
     *
     * <code>string namespaceId = 1;</code>
     * @param value The namespaceId to set.
     * @return This builder for chaining.
     */
    public Builder setNamespaceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      namespaceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *list
     * </pre>
     *
     * <code>string namespaceId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNamespaceId() {
      
      namespaceId_ = getDefaultInstance().getNamespaceId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *list
     * </pre>
     *
     * <code>string namespaceId = 1;</code>
     * @param value The bytes for namespaceId to set.
     * @return This builder for chaining.
     */
    public Builder setNamespaceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      namespaceId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object serviceName_ = "";
    /**
     * <code>string serviceName = 2;</code>
     * @return The serviceName.
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string serviceName = 2;</code>
     * @return The bytes for serviceName.
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string serviceName = 2;</code>
     * @param value The serviceName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string serviceName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceName() {
      
      serviceName_ = getDefaultInstance().getServiceName();
      onChanged();
      return this;
    }
    /**
     * <code>string serviceName = 2;</code>
     * @param value The bytes for serviceName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object agent_ = "";
    /**
     * <code>string agent = 3;</code>
     * @return The agent.
     */
    public java.lang.String getAgent() {
      java.lang.Object ref = agent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        agent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string agent = 3;</code>
     * @return The bytes for agent.
     */
    public com.google.protobuf.ByteString
        getAgentBytes() {
      java.lang.Object ref = agent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string agent = 3;</code>
     * @param value The agent to set.
     * @return This builder for chaining.
     */
    public Builder setAgent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      agent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string agent = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgent() {
      
      agent_ = getDefaultInstance().getAgent();
      onChanged();
      return this;
    }
    /**
     * <code>string agent = 3;</code>
     * @param value The bytes for agent to set.
     * @return This builder for chaining.
     */
    public Builder setAgentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      agent_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object clusters_ = "";
    /**
     * <code>string clusters = 4;</code>
     * @return The clusters.
     */
    public java.lang.String getClusters() {
      java.lang.Object ref = clusters_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clusters_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clusters = 4;</code>
     * @return The bytes for clusters.
     */
    public com.google.protobuf.ByteString
        getClustersBytes() {
      java.lang.Object ref = clusters_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusters_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clusters = 4;</code>
     * @param value The clusters to set.
     * @return This builder for chaining.
     */
    public Builder setClusters(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clusters_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clusters = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearClusters() {
      
      clusters_ = getDefaultInstance().getClusters();
      onChanged();
      return this;
    }
    /**
     * <code>string clusters = 4;</code>
     * @param value The bytes for clusters to set.
     * @return This builder for chaining.
     */
    public Builder setClustersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clusters_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object clientIP_ = "";
    /**
     * <code>string clientIP = 5;</code>
     * @return The clientIP.
     */
    public java.lang.String getClientIP() {
      java.lang.Object ref = clientIP_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientIP_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clientIP = 5;</code>
     * @return The bytes for clientIP.
     */
    public com.google.protobuf.ByteString
        getClientIPBytes() {
      java.lang.Object ref = clientIP_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientIP = 5;</code>
     * @param value The clientIP to set.
     * @return This builder for chaining.
     */
    public Builder setClientIP(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientIP_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clientIP = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientIP() {
      
      clientIP_ = getDefaultInstance().getClientIP();
      onChanged();
      return this;
    }
    /**
     * <code>string clientIP = 5;</code>
     * @param value The bytes for clientIP to set.
     * @return This builder for chaining.
     */
    public Builder setClientIPBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientIP_ = value;
      onChanged();
      return this;
    }

    private int udpPort_ ;
    /**
     * <code>int32 udpPort = 6;</code>
     * @return The udpPort.
     */
    @java.lang.Override
    public int getUdpPort() {
      return udpPort_;
    }
    /**
     * <code>int32 udpPort = 6;</code>
     * @param value The udpPort to set.
     * @return This builder for chaining.
     */
    public Builder setUdpPort(int value) {
      
      udpPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 udpPort = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUdpPort() {
      
      udpPort_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object env_ = "";
    /**
     * <code>string env = 7;</code>
     * @return The env.
     */
    public java.lang.String getEnv() {
      java.lang.Object ref = env_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        env_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string env = 7;</code>
     * @return The bytes for env.
     */
    public com.google.protobuf.ByteString
        getEnvBytes() {
      java.lang.Object ref = env_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        env_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string env = 7;</code>
     * @param value The env to set.
     * @return This builder for chaining.
     */
    public Builder setEnv(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      env_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string env = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnv() {
      
      env_ = getDefaultInstance().getEnv();
      onChanged();
      return this;
    }
    /**
     * <code>string env = 7;</code>
     * @param value The bytes for env to set.
     * @return This builder for chaining.
     */
    public Builder setEnvBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      env_ = value;
      onChanged();
      return this;
    }

    private boolean isCheck_ ;
    /**
     * <code>bool isCheck = 8;</code>
     * @return The isCheck.
     */
    @java.lang.Override
    public boolean getIsCheck() {
      return isCheck_;
    }
    /**
     * <code>bool isCheck = 8;</code>
     * @param value The isCheck to set.
     * @return This builder for chaining.
     */
    public Builder setIsCheck(boolean value) {
      
      isCheck_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isCheck = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsCheck() {
      
      isCheck_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object app_ = "";
    /**
     * <code>string app = 9;</code>
     * @return The app.
     */
    public java.lang.String getApp() {
      java.lang.Object ref = app_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        app_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string app = 9;</code>
     * @return The bytes for app.
     */
    public com.google.protobuf.ByteString
        getAppBytes() {
      java.lang.Object ref = app_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        app_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string app = 9;</code>
     * @param value The app to set.
     * @return This builder for chaining.
     */
    public Builder setApp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      app_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string app = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearApp() {
      
      app_ = getDefaultInstance().getApp();
      onChanged();
      return this;
    }
    /**
     * <code>string app = 9;</code>
     * @param value The bytes for app to set.
     * @return This builder for chaining.
     */
    public Builder setAppBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      app_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tid_ = "";
    /**
     * <code>string tid = 10;</code>
     * @return The tid.
     */
    public java.lang.String getTid() {
      java.lang.Object ref = tid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tid = 10;</code>
     * @return The bytes for tid.
     */
    public com.google.protobuf.ByteString
        getTidBytes() {
      java.lang.Object ref = tid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tid = 10;</code>
     * @param value The tid to set.
     * @return This builder for chaining.
     */
    public Builder setTid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tid = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTid() {
      
      tid_ = getDefaultInstance().getTid();
      onChanged();
      return this;
    }
    /**
     * <code>string tid = 10;</code>
     * @param value The bytes for tid to set.
     * @return This builder for chaining.
     */
    public Builder setTidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tenant_ = "";
    /**
     * <code>string tenant = 11;</code>
     * @return The tenant.
     */
    public java.lang.String getTenant() {
      java.lang.Object ref = tenant_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenant_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tenant = 11;</code>
     * @return The bytes for tenant.
     */
    public com.google.protobuf.ByteString
        getTenantBytes() {
      java.lang.Object ref = tenant_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tenant = 11;</code>
     * @param value The tenant to set.
     * @return This builder for chaining.
     */
    public Builder setTenant(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tenant_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tenant = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenant() {
      
      tenant_ = getDefaultInstance().getTenant();
      onChanged();
      return this;
    }
    /**
     * <code>string tenant = 11;</code>
     * @param value The bytes for tenant to set.
     * @return This builder for chaining.
     */
    public Builder setTenantBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tenant_ = value;
      onChanged();
      return this;
    }

    private boolean healthyOnly_ ;
    /**
     * <code>bool healthyOnly = 12;</code>
     * @return The healthyOnly.
     */
    @java.lang.Override
    public boolean getHealthyOnly() {
      return healthyOnly_;
    }
    /**
     * <code>bool healthyOnly = 12;</code>
     * @param value The healthyOnly to set.
     * @return This builder for chaining.
     */
    public Builder setHealthyOnly(boolean value) {
      
      healthyOnly_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool healthyOnly = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearHealthyOnly() {
      
      healthyOnly_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object cmd_ = "";
    /**
     * <code>string cmd = 13;</code>
     * @return The cmd.
     */
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cmd = 13;</code>
     * @return The bytes for cmd.
     */
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cmd = 13;</code>
     * @param value The cmd to set.
     * @return This builder for chaining.
     */
    public Builder setCmd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cmd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cmd = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearCmd() {
      
      cmd_ = getDefaultInstance().getCmd();
      onChanged();
      return this;
    }
    /**
     * <code>string cmd = 13;</code>
     * @param value The bytes for cmd to set.
     * @return This builder for chaining.
     */
    public Builder setCmdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cmd_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cluster_ = "";
    /**
     * <pre>
     *detail
     * </pre>
     *
     * <code>string cluster = 14;</code>
     * @return The cluster.
     */
    public java.lang.String getCluster() {
      java.lang.Object ref = cluster_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cluster_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *detail
     * </pre>
     *
     * <code>string cluster = 14;</code>
     * @return The bytes for cluster.
     */
    public com.google.protobuf.ByteString
        getClusterBytes() {
      java.lang.Object ref = cluster_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cluster_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *detail
     * </pre>
     *
     * <code>string cluster = 14;</code>
     * @param value The cluster to set.
     * @return This builder for chaining.
     */
    public Builder setCluster(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cluster_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *detail
     * </pre>
     *
     * <code>string cluster = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearCluster() {
      
      cluster_ = getDefaultInstance().getCluster();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *detail
     * </pre>
     *
     * <code>string cluster = 14;</code>
     * @param value The bytes for cluster to set.
     * @return This builder for chaining.
     */
    public Builder setClusterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cluster_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ip_ = "";
    /**
     * <code>string ip = 15;</code>
     * @return The ip.
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ip = 15;</code>
     * @return The bytes for ip.
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ip = 15;</code>
     * @param value The ip to set.
     * @return This builder for chaining.
     */
    public Builder setIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ip_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ip = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearIp() {
      
      ip_ = getDefaultInstance().getIp();
      onChanged();
      return this;
    }
    /**
     * <code>string ip = 15;</code>
     * @param value The bytes for ip to set.
     * @return This builder for chaining.
     */
    public Builder setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ip_ = value;
      onChanged();
      return this;
    }

    private int port_ ;
    /**
     * <code>int32 port = 16;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }
    /**
     * <code>int32 port = 16;</code>
     * @param value The port to set.
     * @return This builder for chaining.
     */
    public Builder setPort(int value) {
      
      port_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 port = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearPort() {
      
      port_ = 0;
      onChanged();
      return this;
    }

    private int pageNo_ ;
    /**
     * <pre>
     *list_service
     * </pre>
     *
     * <code>int32 pageNo = 17;</code>
     * @return The pageNo.
     */
    @java.lang.Override
    public int getPageNo() {
      return pageNo_;
    }
    /**
     * <pre>
     *list_service
     * </pre>
     *
     * <code>int32 pageNo = 17;</code>
     * @param value The pageNo to set.
     * @return This builder for chaining.
     */
    public Builder setPageNo(int value) {
      
      pageNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *list_service
     * </pre>
     *
     * <code>int32 pageNo = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageNo() {
      
      pageNo_ = 0;
      onChanged();
      return this;
    }

    private int pageSize_ ;
    /**
     * <code>int32 pageSize = 18;</code>
     * @return The pageSize.
     */
    @java.lang.Override
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <code>int32 pageSize = 18;</code>
     * @param value The pageSize to set.
     * @return This builder for chaining.
     */
    public Builder setPageSize(int value) {
      
      pageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pageSize = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageSize() {
      
      pageSize_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object groupName_ = "";
    /**
     * <code>string groupName = 19;</code>
     * @return The groupName.
     */
    public java.lang.String getGroupName() {
      java.lang.Object ref = groupName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string groupName = 19;</code>
     * @return The bytes for groupName.
     */
    public com.google.protobuf.ByteString
        getGroupNameBytes() {
      java.lang.Object ref = groupName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string groupName = 19;</code>
     * @param value The groupName to set.
     * @return This builder for chaining.
     */
    public Builder setGroupName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      groupName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string groupName = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupName() {
      
      groupName_ = getDefaultInstance().getGroupName();
      onChanged();
      return this;
    }
    /**
     * <code>string groupName = 19;</code>
     * @param value The bytes for groupName to set.
     * @return This builder for chaining.
     */
    public Builder setGroupNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      groupName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object selectorString_ = "";
    /**
     * <code>string selectorString = 20;</code>
     * @return The selectorString.
     */
    public java.lang.String getSelectorString() {
      java.lang.Object ref = selectorString_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        selectorString_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string selectorString = 20;</code>
     * @return The bytes for selectorString.
     */
    public com.google.protobuf.ByteString
        getSelectorStringBytes() {
      java.lang.Object ref = selectorString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        selectorString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string selectorString = 20;</code>
     * @param value The selectorString to set.
     * @return This builder for chaining.
     */
    public Builder setSelectorString(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      selectorString_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string selectorString = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearSelectorString() {
      
      selectorString_ = getDefaultInstance().getSelectorString();
      onChanged();
      return this;
    }
    /**
     * <code>string selectorString = 20;</code>
     * @param value The bytes for selectorString to set.
     * @return This builder for chaining.
     */
    public Builder setSelectorStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      selectorString_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:run.mone.local.docean.protobuf.ListRequest)
  }

  // @@protoc_insertion_point(class_scope:run.mone.local.docean.protobuf.ListRequest)
  private static final run.mone.local.docean.protobuf.ListRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new run.mone.local.docean.protobuf.ListRequest();
  }

  public static run.mone.local.docean.protobuf.ListRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListRequest>() {
    @java.lang.Override
    public ListRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public run.mone.local.docean.protobuf.ListRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

