// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bo.proto

package run.mone.local.docean.protobuf;

public interface PingMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:run.mone.local.docean.protobuf.PingMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string role = 2;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 2;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <code>int64 time = 3;</code>
   * @return The time.
   */
  long getTime();

  /**
   * <code>string alias = 4;</code>
   * @return The alias.
   */
  java.lang.String getAlias();
  /**
   * <code>string alias = 4;</code>
   * @return The bytes for alias.
   */
  com.google.protobuf.ByteString
      getAliasBytes();

  /**
   * <code>map&lt;string, string&gt; pingMeta = 5;</code>
   */
  int getPingMetaCount();
  /**
   * <code>map&lt;string, string&gt; pingMeta = 5;</code>
   */
  boolean containsPingMeta(
      java.lang.String key);
  /**
   * Use {@link #getPingMetaMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getPingMeta();
  /**
   * <code>map&lt;string, string&gt; pingMeta = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getPingMetaMap();
  /**
   * <code>map&lt;string, string&gt; pingMeta = 5;</code>
   */

  java.lang.String getPingMetaOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; pingMeta = 5;</code>
   */

  java.lang.String getPingMetaOrThrow(
      java.lang.String key);
}
