apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ${CSR_NAME}
spec:
  groups:
    - system:authenticated
  signerName: kubernetes.io/kubelet-serving
  request: ${CSR_BASE64}
  usages:
    - digital signature
    - key encipherment
    - server auth