apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: log-stream
  namespace: ozhera-namespace
  labels:
    app: log-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-stream
  template:
    metadata:
      labels:
        app: log-stream
    spec:
      containers:
      - name: log-stream-container
        image: herahub/opensource-pub:hera-log-stream-v1-release
        env:
          - name: MONE_CONTAINER_S_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
        resources:
          limits:
            cpu: '500m'
            memory: 2Gi
  serviceName: ''
