/*
 * @Description:
 * @Date: 2024-01-22 19:42:57
 * @LastEditTime: 2024-01-23 00:09:17
 */
export default [
  'English',
  'Chinese (Simplified)',
  'Albanian',
  'Arabic',
  'Amharic',
  'Assamese language',
  'Azerbaijani',
  'Evian',
  'Aymara language',
  'Irish',
  'Estonian language',
  'Olya language',
  'Oromo language',
  'Basque language',
  'Belarusian',
  'Bambara language',
  'Bulgarian language',
  'Icelandic',
  'Polish',
  'Bosnian',
  'Persian',
  'Bojepur language',
  'Boer (South African Dutch)',
  'Tatar language',
  'Danish',
  'German',
  'Divish language',
  'Tignian language',
  'Duogelai language',
  'Russian',
  'French',
  'Sanskrit',
  'Filipino language',
  'Finnish',
  'Frisian',
  'Khmer language',
  'Georgian',
  'Gonggen language',
  'Gujarati language',
  'Guarani language',
  'Kazakh language',
  'Haitian Creole',
  'Korean',
  'Hausa language',
  'Dutch',
  'Kyrgyz language',
  'Galician language',
  'Catalan',
  'Czech',
  'Kannada language',
  'Corsican language',
  'Creole language',
  'Croatian',
  'Kechua language',
  'Kurdish (Kurmanji language)',
  'Kurdish (Sorani)',
  'Latin',
  'Latvian language',
  'Laotian',
  'Lithuanian language',
  'Lingla language',
  'Luganda language',
  'Luxembourg language',
  'Rwandan',
  'Romanian',
  'Margash language',
  'Maltese language',
  'Marathi language',
  'Malayalam language',
  'Malay',
  'Macedonian',
  'Matili language',
  'Maori language',
  'Mehtai (Manipur)',
  'Mongolian',
  'Bengali',
  'Mizo language',
  'Burmese',
  'Miao language',
  'South African Cosa language',
  'South African Zulu language',
  'Nepali',
  'Norwegian',
  'Punjabi language',
  'Portuguese',
  'Pashto language',
  'Zicheva language',
  'Qiwei language',
  'Japanese',
  'Swedish',
  'Samoan language',
  'Serbian',
  'Sepeti language',
  'Sesoto language',
  'Sinhalese',
  'Esperanto',
  'Slovak',
  'Slovenian language',
  'Swahili',
  'Scottish Gaelic',
  'Cebu language',
  'Somali',
  'Tajik',
  'Telugu language',
  'Tamil',
  'Thai',
  'Turkish',
  'Turkmen language',
  'Welsh',
  'Uyghur language',
  'Urdu language',
  'Ukrainian',
  'Uzbek language',
  'Spanish',
  'Hebrew',
  'Greek',
  'Hawaiian language',
  'Believe in German',
  'Hungarian',
  'Xiuna language',
  'Armenian',
  'Ibo language',
  'Ilocano language',
  'Italian',
  'Yiddish language',
  'Hindi',
  'Indonesian Sundanese',
  'Indonesian',
  'Indonesian Javanese',
  'Yoruba language',
  'Vietnamese',
  'Chinese (Traditional)',
  'Zongjia language'
]
